### ISSUE TITLE
Cannot modify gdk::EventKey or gdk_sys::GdkEventKey fields

### ISSUE THREAD

**Issue by brackleian** [gtk-rs/gtk-rs#100]
Trying to synthesize Events, generating with `gdk::Event::new(gdk::EventType::KeyPress)` and downcasting to `gdk::EventKey`. There are few setter functions, so it is not easy to modify any of the fields. `gdk::EventKey::as_ref()` returns an immutable reference (to `gdk_sys::GdkEventKey`), and again there are no setter functions for most of the struct members. In particular, for: `window, send_event, time, state, keyval`. There should be `set_window()`, etc., for `gdk::EventKey`, and/or for `gdk_sys::GdkEventKey`, and/or a `gdk::EventKey::as_mut_ref()`. 

Related to the above: the underlying G-object object of the value passed to `set_window()` needs to have its reference count incremented. I'm assuming this should/would happen as part of the `set_window()` functionality, unless there is already a separate library call for this.

**Comment by sdroege** [comment]
So seems like all is actually solved here :)
