### ISSUE TITLE
thread 'main' panicked at 'assertion failed: ::glib::types::instance_of::<Widget>(stash.0 as *const _)'

### ISSUE THREAD

**Issue by bram209** [gtk-rs/gtk-rs#106]
Hello,

I needed global key bindings, so I used the C keybinder lib: https://github.com/engla/keybinder
The binding seems to be working fine, but when I try to call is_visible on a window for example, I get an assertion failed for the glib type

```
    keybinder::bind("<Ctrl>A", move || {
        println!("Works!");
        println!("Visible = {}", window.is_visible());
    });
```

output:

```
Works!
thread 'main' panicked at 'assertion failed: ::glib::types::instance_of::<Widget>(stash.0 as *const _)', /home/bram/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.1.0/src/auto/window.rs:28
```

To be honest, I have no idea what could be causing this.
Does anyone have an idea? 

Sorry for my ignorance

**Comment by sdroege** [comment]
This shouldn't be an issue any more.
