### ISSUE TITLE
Gir submodules alternative

### ISSUE THREAD

**Issue by gkoz** [gtk-rs/gtk-rs#107]
There is a significant drawback to having 'gir' and 'gir-files' submodules in each repo: wasted space and build time when working with several repos at once. It is desirable to find another solution which would retain ease of use (edit `Gir.toml`, `make gir`) and similar control over 'gir' and 'gir-files' revisions used to regenerate code.

**Comment by sdroege** [comment]
We don't have them per module any more as everything's merged into one.
