### ISSUE TITLE
gtk_style_context_get_property not generated

### ISSUE THREAD

**Issue by BrainBlasted** [gtk-rs/gtk-rs#124]
This might not be generated because it's similar to g_object_get_property? Despite the naming it does not have the same functionality. Rather, it gets the **style property** of the Widget. Without it widgets like [Granite's avatar widget](https://github.com/elementary/granite/blob/6d0dac21b728b1ed28baaf38a004dca378559435/lib/Widgets/Avatar.vala) can't be implemented in Rust.

**Comment by GuillaumeGomez** [comment]
It's already generated so closing.
