### ISSUE TITLE
Documentation: links are broken for implementors of traits in gtk::prelude

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk-rs#125]
When you go to any trait in gtk::prelude (e.g. [ButtonExt](https://gtk-rs.org/docs/gtk/prelude/trait.ButtonExt.html)) and then click on one of the implementors (e.g. [Button](https://gtk-rs.org/docs/gtk/prelude/struct.Button.html)) you get a 404 error.

**Comment by bilelmoussaoui** [comment]
I think this was resolved in the latest docs: https://gtk-rs.org/gtk-rs/git/docs/gtk/prelude/trait.ButtonExt.html

**Comment by bilelmoussaoui** [comment]
Can you confirm that?

**Comment by Hofer-Julian** [comment]
Yes, indeed :)
