### ISSUE TITLE
Add support for composite templates.

### ISSUE THREAD

**Issue by gm666q** [gtk-rs/gtk-rs#126]
Add support for using composite templates from Builder/Glade.

**Comment by sdroege** [comment]
There's some work being done for this in https://gitlab.gnome.org/World/Solanum/-/merge_requests/22 by @BrainBlasted

**Comment by sdroege** [comment]
There is an implementation for GTK4 now at https://github.com/gtk-rs/gtk4-rs/pull/51 . This could be merged exactly the same into gtk(3) too if someone wants to make use of composite templates.
