### ISSUE TITLE
glib:  virtual methods of *Impl traits take parent type

### ISSUE THREAD

**Issue by ids1024** [gtk-rs/gtk-rs#14]
This is a pain for sub-classing ergonomics, since implementations are likely to want to downcast to the right type.

One possible solution might be to require implementers of `ObjectSubclass` to define a `glib_wrapper!` and use that. Don't know if that would lead to any type system issues, and it would make things more complicated.

I've experimented a bit with (unstable) associated type defaults, but I don't think that will quite work because there currently isn't a default we can assume will implement the parent's `*Ext` trait, but also interfaces.

**Comment by sdroege** [comment]
> One possible solution might be to require implementers of `ObjectSubclass` to define a `glib_wrapper!` and use that. Don't know if that would lead to any type system issues, and it would make things more complicated.

I would require exactly that from implementers: Use `glib_wrapper!` to define the wrapper types and all the other boilerplate code.

Do you see a problem with doing so?

**Comment by ids1024** [comment]
That's my inclination, particularly now that the boilerplate for using `glib_wrapper!` for a subclass if fairly minimal.

I think it should work fine.

**Comment by ids1024** [comment]
Relatedly: figure out some way for the wrapper type to not need `@extends` and `@implements`.

**Comment by sdroege** [comment]
Then let's give it a try. It will be a minor annoyance for people writing GStreamer plugins as previously `glib_wrapper!` and all that was not needed for them, but for GTK use-cases this shouldn't mean any additional work and simplify everything.

Let me know if you want to take a look at this, otherwise I'll get to that in a few weeks after I got my other things out of the way (GValue handling / subclass properties).

**Comment by sdroege** [comment]
> Relatedly: figure out some way for the wrapper type to not need `@extends` and `@implements`.

That would be great but I don't see how that could be possible unless we put the whole subclassing user code into a proc-macro :) Let's worry about that in a separate ticket though.

**Comment by ids1024** [comment]
> That would be great but I don't see how that could be possible unless we put the whole subclassing user code into a proc-macro :)

My thought was another magic trait that is implemented in `glib_wrapper!` for `ObjectSubclass` wrappers indicating what type implementing `ObjectSubclass` they wrap. Then having blanket `IsA` implementations based on that.

The main issue is that it would conflict with other blanket implementations, if there were reason to have others.

**Comment by ids1024** [comment]
This seems to be potentially awkward without implied bounds (https://github.com/rust-lang/rust/issues/44491), which is dependent on chalk. Not sure what the timeline for that is. Or the associated type bounds feature (https://github.com/rust-lang/rust/issues/52662, which currently works on nightly with a feature flag), which in theory is meant to be syntax sugar but seems to effectively provide implied bounds for this case...

```rust
trait ObjectSubclass ... {
    ...
   type ObjectType;
    ...
}

```rust
pub trait ObjectImpl: ObjectSubclass + ObjectImplExt
where
    Self::Type: IsA<Object> {
    ...
}
```

This works, but the `Self::Type: IsA<Object>` bound has to be explicitly added everywhere `ObjectImpl` is used

So things like this fail to compile without adding that `where` bound:

```rust
pub trait ApplicationImpl: ObjectImpl + ApplicationImplExt {
    ...
}
```

This is annoying, but I guess it probably doesn't have to be a blocker...

**Comment by ids1024** [comment]
WIP implementation: https://github.com/gtk-rs/gtk-rs/pull/27

It seems fine not enforce such a type bound in `ObjectImpl`. By adding another unsafe trait, the code enforces that `Self::Type` is in fact a glib wrapper around the subclass being defined.
