### ISSUE TITLE
The function Pixbuf::new_from_vec

### ISSUE THREAD

**Issue by gbersac** [gtk-rs/gtk-rs#145]
Trying to use that function, I had a really hard time using and understanding [it](https://github.com/gtk-rs/gdk-pixbuf/blob/master/src/pixbuf.rs#L34). What are the meaning of the arguments ? There is no documentation.
### `colorspace`

What is it ? For `new` it is `Color space for image`. I interpreted it as being the number of colour (red, green, blue) but this is supposed to be [n_channels](https://github.com/gtk-rs/gdk-pixbuf/blob/master/src/pixbuf.rs#L41). So I don't have a clue what it truly is.

I found this on the [gdk documentation website](https://developer.gnome.org/gdk-pixbuf/unstable/gdk-pixbuf-The-GdkPixbuf-Structure.html#GdkColorspace) :

```
The colorspace in which the samples are interpreted.
Flags: Read / Write / Construct Only
Default value: GDK_COLORSPACE_RGB
```

If I understand its value have to be `GDK_COLORSPACE_RGB`, is it useful to have this as argument ? If it is useful, why not create a `Colorspace` enum ?
### `bits_per_sample`

Since there is this line in the code :

``` rust
assert!(bits_per_sample == 8);
```

There is only one correct value for `bits_per_sample`. Why not remove it from the argument of the list ?
### `row_stride`

I had to go on the [gdk documentation](https://developer.gnome.org/gdk-pixbuf/unstable/gdk-pixbuf-Image-Data-in-Memory.html#gdk-pixbuf-new-from-data) to understand what this argument is :

```
Distance in bytes between row starts
```

Should be in the doc !
### Conclusion

I'd agree to contribute but I don't know how the documentation of this crate is generated. Does regular doc comments works ?

**Comment by sdroege** [comment]
There's `Pixbuf::from_mut_slice()` (you can pass a `Vec<u8>` in there) and various other similar functions now.
