### ISSUE TITLE
How to access the Pixbuf data without unsafe?

### ISSUE THREAD

**Issue by RazrFalcon** [gtk-rs/gtk-rs#147]
The `Pixbuf::get_pixels` method is marked as unsafe and `PixbufExt::read_pixel_bytes` is >=2.32 (and I have 2.30).

How can I access the Pixbuf data in read-only mode?

**Comment by sdroege** [comment]
The `unsafe` function and the `read_pixel_bytes()` are the only ways to get access to the pixbuf data. Others would be potentially unsound.
