### ISSUE TITLE
Update README.md to also link to the gtk4 bindings and potentially gstreamer-rs and gitlab.gnome.org/World/Rust

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs#15]
@bilelmoussaoui @GuillaumeGomez What do you think?

**Comment by GuillaumeGomez** [comment]
gtk4 bindings: ok, but the rest I'm not sure. Why linking to gstreamer-rs for example?

**Comment by sdroege** [comment]
Bindings for other languages are usually a collection of everything that exists, not just a selected set of libraries like we do here. So people might come here to find e.g. the GStreamer or [libhandy](https://gitlab.gnome.org/World/Rust/libhandy-rs) or [sourceview-4](https://gitlab.gnome.org/World/Rust/sourceview4-rs) bindings.

It gives better visibility to users that there's also lots of other stuff out there that builds on top of `glib-rs` and integrates well with it, and the list of crates in here is not everything there is.

Think of it like the "Other customers who bought this often bought it together with that other product" feature on Amazon ;)

**Comment by GuillaumeGomez** [comment]
Well, for the other gtk "extensions", not a big issue but gstreamer-rs seems a bit out of context here. It's definitely not the same target after all (GUI vs multimedia).

**Comment by sdroege** [comment]
glib, gio, cairo, pango, graphene for example are also not GUI and about half of the GNOME applications using gtk-rs right now also use GStreamer :man_shrugging:

**Comment by bilelmoussaoui** [comment]
gtk4 uses gstreamer as for stuff like GtkVideo so it doesn't hurt to mention it. Otherwise I think we should definitely mention sourceview4-rs to avoid people using the sourceview 3 bindings.

**Comment by GuillaumeGomez** [comment]
Seems like valid arguments. Then all good for me!
