### ISSUE TITLE
Atk usage examples

### ISSUE THREAD

**Issue by RastislavKish** [gtk-rs/gtk-rs#152]
Hi,
I'm new to gtk-rs, I have installed everything necessary and made an test window with a button following the example on project's website.
It seems to work as expected when controlled by mouse, however the window is completely inaccessible for screenreaders.
I'm blind myself, so this is very important library's aspect to me.
I have found atk, made sure that it's installed by explicitly specifying it as a dependency, but I'm not sure, what to do next.

Are there any usage examples?

I'm using Windows 10 pro 1809 64-bit, Rust 1.39, tested with Jaws and Nvda screenreaders.

Thanks!

**Comment by sdroege** [comment]
There's https://github.com/gtk-rs/gtk-rs/blob/master/examples/src/bin/accessibility.rs
