### ISSUE TITLE
Fails to chain up multiple vfunc implementation

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs#162]
I have got an issue while working on adding subclassing support to libhandy-rs. In libhandy, there's widget ActionRow that subclasses ListBoxRow & re-defines the activate vfunc

```rust
pub struct HdyActionRowClass {
    pub parent_class: gtk::GtkListBoxRowClass,
    pub activate: Option<unsafe extern "C" fn(*mut HdyActionRow)>,
    pub padding: [gpointer; 4],
}
```

Having something similar to 

```rust
use handy_sys;

use glib::subclass::prelude::*;
use glib::translate::*;
use glib::Cast;

use gtk::subclass::list_box_row::ListBoxRowImpl;
use gtk::ListBoxRow;
use ActionRow;

pub trait ActionRowImpl: ActionRowImplExt + ListBoxRowImpl {
    fn activate(&self, row: &Self::Type) {
        self.parent_activate(row)
    }
}

pub trait ActionRowImplExt: ObjectSubclass {
    fn parent_activate(&self, row: &Self::Type);
}

impl<T: ActionRowImpl> ActionRowImplExt for T {
    fn parent_activate(&self, row: &Self::Type) {
        unsafe {
            let data = T::type_data();
            let parent_class =
                data.as_ref().get_parent_class() as *mut handy_sys::HdyActionRowClass;
            if let Some(f) = (*parent_class).activate {
                f(row.unsafe_cast_ref::<ActionRow>().to_glib_none().0)
            }
        }
    }
}

unsafe impl<T: ActionRowImpl> IsSubclassable<T> for ActionRow {
    fn override_vfuncs(class: &mut glib::Class<Self>) {
        <ListBoxRow as IsSubclassable<T>>::override_vfuncs(class);

        let klass = class.as_mut();
        klass.activate = Some(row_activate::<T>);
    }
}

unsafe extern "C" fn row_activate<T: ActionRowImpl>(ptr: *mut handy_sys::HdyActionRow) {
    let instance = &*(ptr as *mut T::Instance);
    let imp = instance.get_impl();
    let wrap: Borrowed<ActionRow> = from_glib_borrow(ptr);

    imp.activate(wrap.unsafe_cast_ref())
}
```

Except it doesn't, as there are two different activate methods, one defined in ActionRowImpl & the other in ListBoxRowImpl, normally, the inner-most (the one in HdyActionRowImpl) should be used. I'm not sure if that's an issue per see. Making HdyActionRow not subclass GtkListBoxRow is problematic because then gtk adds a listboxrow wrapper around the widget and causes issues for how it's intended to be used

**Comment by sdroege** [comment]
Check gstreamer-rs: `ElementImpl::query` vs. `BaseSrc::query`. You need to be careful with calling the function from the correct trait when chaining up, or things will become very unhappy.

**Comment by sdroege** [comment]
Similarly problematic in C++, Java, etc. It's not a good idea to have something like this in API that is supposed to be used from bindings.

**Comment by bilelmoussaoui** [comment]
Nice, thanks for the pointer, that works fine

**Comment by sdroege** [comment]
Generally for all these subclassing things, look at gstreamer-rs. That covers probably all the cases you might run into :)
