### ISSUE TITLE
Document how to cross compile for windows

### ISSUE THREAD

**Issue by adnan449** [gtk-rs/gtk-rs#187]
Cross compilation for windows is a major requirement for many developers. Especially [from Linux for Windows 64 Bit](https://github.com/gotk3/gotk3/wiki/Cross-Compiling#from-linux-for-windows-64-bit).

Even a simple wiki page should do, I asked how to do this in stackoverflow too but haven't had any luck unfortunately.

**Comment by sdroege** [comment]
That would be useful to have, but as none of the gtk-rs developers are using Windows this would have to be written by someone who actually does use Windows.

**Comment by mehmooda** [comment]
Not sure about other distros.

But on fedora.

dnf install mingw64-gtk3
mingw64-env
cargo build --target x86_64-pc-windows-gnu

**Comment by InfRandomness** [comment]
Hi,
it looks like an error was made in the writing because it is at one point said to run "dnf install mingw64-gcc mingw64-pango mingw64-poppler mingw-w64-gtk3", the latest package name (mingw-w64-gtk3) isn't correct because it doesn't exist, however mingw64-gtk3 does exist

**Comment by sdroege** [comment]
Do you want to provide a PR for fixing this in the docs?

**Comment by InfRandomness** [comment]
Sure

**Comment by InfRandomness** [comment]
fixed in #gtk-rs/gtk-rs.github.io#189

**Comment by InfRandomness** [comment]
While I was also experimenting in a VM, I experienced an issue where libpthread.a was missing, this library not being shipped by the packages already listed (and neither by mingw64-winpthreads), so it might be needed to install mingw64-winpthreads-static.

**Comment by cars10** [comment]
BTW, there is a tutorial on the website:
https://gtk-rs.org/docs-src/tutorial/cross

**Comment by InfRandomness** [comment]
I saw [that crate](https://github.com/rust-embedded/cross) earlier and thought it could people cross-compiling their application.
I've already created a Dockerfile (based on fedora:33) (and am willing to create other Dockerfile depending on other Linux distros if needed) that people could use alongside cross to make the process easier,
would this be worth getting a place in https://gtk-rs.org/docs-src/tutorial/cross ?

**Comment by adnan449** [comment]
I am using Fedora Linux and I have followed [the official instructions](https://gtk-rs.org/docs-src/tutorial/cross) and I am having issues.

 My cargo build command in my Makefile is as follows:

```Makefile
build-windows-from-fedora:
	export PKG_CONFIG_ALLOW_CROSS=1
	export MINGW_PREFIX=/usr/x86_64-w64-mingw32/sys-root/mingw/
	export PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig
	cargo build --target=x86_64-pc-windows-gnu --release
```

Calling those commands gives me the following error:

```
$ make build-windows-from-fedora 
export PKG_CONFIG_ALLOW_CROSS=1
export MINGW_PREFIX=/usr/x86_64-w64-mingw32/sys-root/mingw/
export PKG_CONFIG_PATH=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig
cargo build --target=x86_64-pc-windows-gnu --release
   Compiling glib-sys v0.10.1
error: failed to run custom build command for `glib-sys v0.10.1`

Caused by:
  process didn't exit successfully: `/home/bruce3434/proj/tempconv/target/release/build/glib-sys-eb2938807257b78a/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=GLIB_2.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  pkg-config has not been configured to support cross-compilation.

                  Install a sysroot for the target platform and configure it via
                  PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
                  cross-compiling wrapper for pkg-config and set it via
                  PKG_CONFIG environment variable.
make: *** [Makefile:5: build-windows-from-fedora] Error 101
```

I am not sure what was meant by 

> Install a sysroot for the target platform and configure it via
 PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
 cross-compiling wrapper for pkg-config and set it via
 PKG_CONFIG environment variable.

Any help would be greatly appreciated.

**Comment by adnan449** [comment]
I just realized `mingw64-winpthreads-static` package is also required for Fedora.

**Comment by InfRandomness** [comment]
Hi, if you've red the whole thread, this was said here : https://github.com/gtk-rs/gtk-rs/issues/187#issuecomment-751454832

**Comment by adnan449** [comment]
I'm going to close this issue since I was successful in creating a windows binary following this tutorial: https://gtk-rs.org/docs-src/tutorial/cross

I suspect some time in future this will stop working due to how linux packages work (future incompatibility) but that is a problem for upstream GTK to solve. As [recently suggested](https://www.reddit.com/r/gnome/comments/lz09eh/what_are_the_reasons_behind_gtk_not_shipping_a/gpxqe2d?utm_source=share&utm_medium=web2x&context=3) the GTK team is working on improving the process of local compilation too :)

**Comment by jhoneybee** [comment]
How do i compile webkitgtk ?

@adnan449  @InfRandomness

**Comment by InfRandomness** [comment]
On what linux distribution ? You probably need a mingw package

**Comment by jhoneybee** [comment]
thank you very much.
