### ISSUE TITLE
gio ActionMap/ActionGroup subclassing support

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs#190]
It's pretty useful to be able to subclass gio::ActionMap when creating a custom widget with it's own actions group instead of having to add an actions field into your `imp::WidgetStruct`

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gobject-subclass/tree/master/gio-subclass for the very old version of those. They need some special care because of all the `transfer none` return values.
