### ISSUE TITLE
glib: Can SignalHandlerId implement the Copy trait? 

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk-rs#193]
The relevant bits

```rust
/// The id of a signal that is returned by `connect`.
#[derive(Debug, Eq, PartialEq)]
pub struct SignalHandlerId(NonZeroU64);

impl ToGlib for SignalHandlerId {
    type GlibType = c_ulong;

    #[inline]
    fn to_glib(&self) -> c_ulong {
        self.0.get() as c_ulong
    }
}

impl FromGlib<c_ulong> for SignalHandlerId {
    #[inline]
    fn from_glib(val: c_ulong) -> SignalHandlerId {
        assert_ne!(val, 0);
        SignalHandlerId(unsafe { NonZeroU64::new_unchecked(val as u64) })
    }
}
```

Since to me seems that SignalHandler is a glorified `u64`, it could easily implement Copy or at least Clone. Is there any reason it can't implement them, or for more conveniennce to be a u64 directly? Granted, it makes no sense to add or multiply handlers ids, but it would be convenient.

Context: I just had an issue where I needed to use a RefCell / OnceCell to store this info on a non mutable struc, but later I was not able to run `self.disconnect(handler_id)` since the type i got from those was `&SignalHandlerId` and I found no way of getting back the `SignalHandlerId` from it without calling both `from_glib` and `to_glib` to store the internal `c_ulong` as a `u64`.

**cc** @bilelmoussaoui .

**Comment by A6GibKm** [comment]
Alternative route: 

Could disconnect accept both `&SignalHandlerId` and `SignalHandlerId`?

**Comment by sdroege** [comment]
> but later I was not able to run `self.disconnect(handler_id)` since the type i got from those was `&SignalHandlerId`

Store it in an `Option` and use `Option::take()` to take it out of the `Option` exactly once.

> Is there any reason it can't implement them, or for more conveniennce to be a u64 directly?

Signal handler ids can only be disconnected once. If you disconnect the same signal handler id multiple times you can cause all kinds of bugs, including disconnecting other signal handlers than your own.

**Comment by A6GibKm** [comment]
Sounds good to me, I just wish this was documented somewhere.

**Comment by sdroege** [comment]
Where would you have expected this documentation? Maybe send a PR that adds it exactly in that place :)

Also the existence of `Option::take` seems to be generally missed by many...

**Comment by A6GibKm** [comment]
> Where would you have expected this documentation? Maybe send a PR that adds it exactly in that place :)

Here 
```
/// The id of a signal that is returned by `connect`.
#[derive(Debug, Eq, PartialEq)]
pub struct SignalHandlerId(NonZeroU64)
```
But I don't know how common is to refer to the implementation when in doubt for the user. I will think about it and if I find a proposal do the PR.

> Also the existence of Option::take seems to be generally missed by many...

Yes, it is missed by many because every single element of std has a gigantic api.

Please note that as long as the traits ToGlib and FromGlib are public, nothing stops me from doing multiple copies and storing as a u64.

**Comment by GuillaumeGomez** [comment]
> Please note that as long as the traits ToGlib and FromGlib are public, nothing stops me from doing multiple copies and storing as a u64.

Yes, just like you can actually mutate anything by going through cast. You can, but it's up to you. :)

**Comment by A6GibKm** [comment]
I don't. but I have already spend 4 hours already trying to disconnect a signal without success.

**Comment by GuillaumeGomez** [comment]
`your_object.disconnect(signal_handler);` doesn't work?

**Comment by A6GibKm** [comment]
I need to store it inside a RefCell or a OnceCell since the struct which has to store it can't be mutable.

```
pub struct Foo {
   ...
    connection_id: OnceCell<SignalHandlerId>,
}
...
impl Foo {
    fn get_connection_id(&self) -> Option<SignalHandlerId> {
        self.connection_id.get().take()
    }
}
```

I don't really care about how to implement it, but I need a impl to get the signal to use later.

**Comment by GuillaumeGomez** [comment]
Just a question: do you need to disconnect when you receive an event in another `connect_*`? If so, you can just move your signal handler ID in this closure and you're done. :)

**Comment by A6GibKm** [comment]
Yes. It is 100% needed to disconnect, and the part which disconnect is not on a closure, and in another file.

**Comment by A6GibKm** [comment]
Instead of talking in abstract here is the actual [MR](https://gitlab.gnome.org/haecker-felix/souk/-/merge_requests/36). This could be achieved in many ways without the disconnect, but having this disconnect (but for a different widget) would also solve an unrelated long standing [issue](https://gitlab.gnome.org/haecker-felix/souk/-/issues/9).

**Comment by sdroege** [comment]
I think what you're doing there perfectly makes sense, just that you have to store your signal handlers in some kind of `RefCell<Option<_>>` so you can take them out exactly once from an immutable context.

I was asking where you would put the documentation because I wouldn't know where I would've looked for that in the documentation :) If you think it would make sense on the type directly, let's add a paragraph there.

Do you want to prepare a PR for that?

**Comment by A6GibKm** [comment]
I would gladly prepare one,  as soon as I am able to get the signal out of the `RefCell<Option<T>>`.

**Comment by sdroege** [comment]
See my comment on your MR :)
