### ISSUE TITLE
gtk-macros: Need to add license headers to the files

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs#209]
Same for gtk4-macros.

@bilelmoussaoui @BrainBlasted @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'll add a check to ensure that all files have a license header I think.

**Comment by GuillaumeGomez** [comment]
Fixed by https://github.com/gtk-rs/gtk-rs/pull/217.
