### ISSUE TITLE
Corresponding g_signal_connect_swapped fucntion

### ISSUE THREAD

**Issue by Kofituo** [gtk-rs/gtk-rs#224]
I don't seem to find which rust function corresponds to `g_signal_connect_swapped` and `gtk_window_set_child`. I'm trying to convert this code to rust.
`static void
activate (GtkApplication *app,
          gpointer        user_data)
{
  GtkWidget *window;
  GtkWidget *button;
  GtkWidget *box;

  window = gtk_application_window_new (app);
  gtk_window_set_title (GTK_WINDOW (window), "Window");
  gtk_window_set_default_size (GTK_WINDOW (window), 200, 200);

  box = gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
  gtk_window_set_child (GTK_WINDOW (window), box);

  button = gtk_button_new_with_label ("Hello World");
  g_signal_connect (button, "clicked", G_CALLBACK (print_hello), NULL);
  g_signal_connect_swapped (button, "clicked", G_CALLBACK (gtk_window_destroy), window);
  gtk_box_append (GTK_BOX (box), button);

  gtk_widget_show (window);
}` 
from here https://developer.gnome.org/gtk4/unstable/ch01s02.html

**Comment by GuillaumeGomez** [comment]
It's gtk3 here, not gtk4 (which is [here](https://github.com/gtk-rs/gtk4-rs), but since it's the same answer for both, here we go!

This is a C macro so we don't have it. But take a look at the documentation and you can do it pretty easily: https://developer.gnome.org/gobject/stable/gobject-Signals.html#g-signal-connect-swapped

However, it could be interesting to add it into our source code. Would you be interested into adding it?

**Comment by sdroege** [comment]
Why do you need `connect_swapped()`? That only really makes sense in C because it doesn't have closures and otherwise this would be annoying to write.

The Rust equivalent would be to simply use a closure instead:

```rust
let window = ...;
[...]
let window_clone = window.clone(); // It's fine to clone here although it creates a circular reference due to how closing windows works in GTK
button.connect_clicked(move |_button| {
    window_clone.close();
});
[...]

window.show_all();
```

**Comment by Kofituo** [comment]
> It's gtk3 here, not gtk4 (which is [here](https://github.com/gtk-rs/gtk4-rs), but since it's the same answer for both, here we go!
> 
> This is a C macro so we don't have it. But take a look at the documentation and you can do it pretty easily: https://developer.gnome.org/gobject/stable/gobject-Signals.html#g-signal-connect-swapped
> 
> However, it could be interesting to add it into our source code. Would you be interested into adding it?

Okay I think I might be able to add it

**Comment by Kofituo** [comment]
> Why do you need `connect_swapped()`? That only really makes sense in C because it doesn't have closures and otherwise this would be annoying to write.
> 
> The Rust equivalent would be to simply use a closure instead:
> 
> ```rust
> let window = ...;
> [...]
> let window_clone = window.clone(); // It's fine to clone here although it creates a circular reference due to how closing windows works in GTK
> button.connect_clicked(move |_button| {
>     window_clone.close();
> });
> [...]
> 
> window.show_all();
> ```

Let me try this too

**Comment by Kofituo** [comment]
> > Why do you need `connect_swapped()`? That only really makes sense in C because it doesn't have closures and otherwise this would be annoying to write.
> > The Rust equivalent would be to simply use a closure instead:
> > ```rust
> > let window = ...;
> > [...]
> > let window_clone = window.clone(); // It's fine to clone here although it creates a circular reference due to how closing windows works in GTK
> > button.connect_clicked(move |_button| {
> >     window_clone.close();
> > });
> > [...]
> > 
> > window.show_all();
> > ```
> 
> Let me try this too



> Why do you need `connect_swapped()`? That only really makes sense in C because it doesn't have closures and otherwise this would be annoying to write.
> 
> The Rust equivalent would be to simply use a closure instead:
> 
> ```rust
> let window = ...;
> [...]
> let window_clone = window.clone(); // It's fine to clone here although it creates a circular reference due to how closing windows works in GTK
> button.connect_clicked(move |_button| {
>     window_clone.close();
> });
> [...]
> 
> window.show_all();
> ```

Are there any downsides to cloning of the widgets?

**Comment by sdroege** [comment]
> Are there any downsides to cloning of the widgets?

You need to be careful to not create reference cycles, which would result in memory leaks. To avoid that you would use weak references (`downgrade()` / `update()` instead of `clone()`). In this case here it's not actually a problem though (you create a reference cycle but due to how GTK works it will be resolved directly when calling `close()`).

**Comment by Kofituo** [comment]
> > Are there any downsides to cloning of the widgets?
> 
> You need to be careful to not create reference cycles, which would result in memory leaks. To avoid that you would use weak references (`downgrade()` / `update()` instead of `clone()`). In this case here it's not actually a problem though (you create a reference cycle but due to how GTK works it will be resolved directly when calling `close()`).

Following your example I get this error
`fn on_activate(app: &gtk::Application) {
    let window = gtk::ApplicationWindow::new(app);
    window.set_title("Window");
    window.set_default_size(200, 200);
    let button_box = gtk::ButtonBox::new(gtk::Orientation::Horizontal);
    window.add(&button_box);
    let button = gtk::Button::with_label("Hello World");
    let clone = window.clone();
    button.connect_clicked(move |_button| {
        println!("hi");
        clone;
    });

    //connect_clicked_swap!(button, window, ApplicationWindow::close);
    button_box.add(&button);
    window.show_all()
}`

error[E0507]: cannot move out of `clone`, a captured variable in an `Fn` closure
  --> src/main.rs:19:9
   |
16 |     let clone = window.clone();
   |         ----- captured outer variable
...
19 |         clone;
   |         ^^^^^ move occurs because `clone` has type `ApplicationWindow`, which does not implement the `Copy` trait

**Comment by Kofituo** [comment]
> > Are there any downsides to cloning of the widgets?
> 
> You need to be careful to not create reference cycles, which would result in memory leaks. To avoid that you would use weak references (`downgrade()` / `update()` instead of `clone()`). In this case here it's not actually a problem though (you create a reference cycle but due to how GTK works it will be resolved directly when calling `close()`).

So something like the example given here https://www.gtk.org/docs/language-bindings/rust ?

**Comment by sdroege** [comment]
Yes, but also there it's not strictly required.

**Comment by Kofituo** [comment]
> Yes, but also there it's not strictly required.

Okay got it
