### ISSUE TITLE
Support usize / isize in glib::Value

### ISSUE THREAD

**Issue by ArekPiekarz** [gtk-rs/gtk-rs#229]
In glib, `Value` currently has poor support for `usize` / `isize`. The traits `FromValue` / `FromValueOptional` / `SetValue` are implemented for many primitive types [here](https://github.com/gtk-rs/gtk-rs/blob/master/glib/src/value.rs#L1054), but not for the ones mentioned in the title. Because of that when I want to store them in a `gtk::TreeModel`, I have to cast them to `u32` or `u64`.

Would it be possible to add support for them? I think the closest equivalent in C/C++ would be `size_t`.

**Comment by sdroege** [comment]
There's no support for storing `size_t` / `ssize_t` in `GValue` unfortunately. That's something that would have to be added to the C library first.

**Comment by sdroege** [comment]
As such, first start with creating an issue here: https://gitlab.gnome.org/GNOME/glib/-/issues/new

I don't think chances are very high for that to be added to GLib though.
