### ISSUE TITLE
Bind types needed for implementing a pixbuf loader

### ISSUE THREAD

**Issue by pbor** [gtk-rs/gtk-rs#241]
In https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/457 I am experimenting with porting rsvg's gdkpixbufloader to rust.

As can be seen in that patch, I had to manually bind various types (`GdkPixbufModulePattern`, `GdkPixbufFormat`, `GdkPixbuf.Module`, etc).

The first question is: does these bindings belong in `gdk_pixbuf_sys`? In other words, is implementing a pixbuf loader in scope for this crate or we want to only expose api for applications using the gdkpixbuf API?

If the answer is yes, I am available to try to provide a patch, but I will need some guidance :)
Should I just add those types to `manual.rs` or do we expect gir generation to be able to deal with those and the fixes need to be in the annotations?

**Comment by sdroege** [comment]
> The first question is: does these bindings belong in `gdk_pixbuf_sys`?

Yes but the bigger question would be why that API is not in the .gir file. If it was then it would already be in `gdk-pixbuf-sys`.

Best to check that first with the `gdk-pixbuf` maintainers. If that's all intentional and correct then you'd have to add manual `-sys` bindings for this.

**Comment by pbor** [comment]
well, the "api" is a bunch of C structs with public fields, some of which are strings and function pointers... no idea if gir can support any of that :)

**Comment by sdroege** [comment]
Works for other libraries :)

**Comment by pbor** [comment]
https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/167

**Comment by sdroege** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/blob/fc2d7fc4d06152517d77ad6049ea4ec943ceb268/gstreamer/sys/src/lib.rs#L2319-2334 is an example for such a struct in GStreamer that is used for exactly the same purpose.

In https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/blob/fc2d7fc4d06152517d77ad6049ea4ec943ceb268/gstreamer/src/subclass/plugin_1_12.rs it's wrapped in safe API for defining a GStreamer plugin.

**Comment by pbor** [comment]
The .gir changes have been merged upstream. How does it work? Shall we wait for a release or I can generate from gir locally and then open a MR?

**Comment by sdroege** [comment]
Create a PR [here](https://github.com/gtk-rs/gir-files/) and once that is merged update the submodule here.

**Comment by pbor** [comment]
done... not sure why formatting is so different

**Comment by pbor** [comment]
Ok, I think I fixed things... I see regen check still failing, but I guess that is normal?

This required two extra changes
1. in the gir files I had to add a fix in `fix.sh` to replace usage of `GModule` with a plain `gpointer`
2. in the test files I had to `#define GDK_PIXBUF_ENABLE_BACKEND` so that the test could check the size of the structs

**Comment by sdroege** [comment]
>  I see regen check still failing, but I guess that is normal?

Yes until the `gir-files` PR is merged this is normal.

> This required two extra changes
> 
>     1. in the gir files I had to add a fix in `fix.sh` to replace usage of `GModule` with a plain `gpointer`

This seems fine until we add `gmodule` bindings :)

> in the test files I had to `#define GDK_PIXBUF_ENABLE_BACKEND` so that the test could check the size of the structs

That's a bit annoying as that change will be overridden again when running `generator.py` or not?

**Comment by pbor** [comment]
No, the define is in `manual.h` so I assume it will not be overwritten

**Comment by sdroege** [comment]
Ah, not a problem then :)
