### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs#244]
See https://github.com/gtk-rs/gtk4-rs/issues/74 . Especially the minimum supported Rust version should be documented.

CC @bilelmoussaoui

**Comment by sdroege** [comment]
Something like what @bilelmoussaoui did for gtk4-rs would be useful here.

**Comment by GuillaumeGomez** [comment]
What are you referring to?

**Comment by sdroege** [comment]
https://github.com/gtk-rs/gtk4-rs/pull/189

**Comment by GuillaumeGomez** [comment]
I see. Then I'll update my PR to "part of #244" instead.
