### ISSUE TITLE
Consider replacing futures dependency with sub-crates

### ISSUE THREAD

**Issue by jplatte** [gtk-rs/gtk-rs#251]
glib currently depends on `futures`, pulling in all of [`futures-channel`, `future-core`, `futures-executor`, `futures-io`, `futures-sink`, `futures-task` and `futures-tokio`] as transitive dependencies. Unless you actually use functionality from all of those crates, it would be good to only depend on the specific sub-crates whose functionality is being used.

**Comment by jplatte** [comment]
Actually just found out the futures-util crate pulls in pretty much all other futures-* crates. This may not be worth it.

**Comment by sdroege** [comment]
Yeah that was the reason back then why I didn't bother. Feel free to do this though if you feel motivated :)
