### ISSUE TITLE
Provide wrapper around `glib-compile-resources`

### ISSUE THREAD

**Issue by ids1024** [gtk-rs/gtk-rs#259]
It can be useful to embed resources using `glib-compile-resources` in `build.rs`, then using `include_bytes!` to include it in the executable. (Equivalent to using `glib-compile-resources --generate-source` in C).

This requires a certain amount of boilerplate, so it could be helpful for gtk-rs to provide a wrapper for it, unless there's already something I'm unaware of.

**Comment by bilelmoussaoui** [comment]
As a bunch of people already asked on IRC on how to do that, having a helper along with an example would be nice.

**Comment by ids1024** [comment]
It should produce a `cargo:rerun-if-changed=` line for every file listed in the `.gresource.xml` file. Though that's a bit awkward since it would require an xml parser.

**Comment by bilelmoussaoui** [comment]
Well, if you really want that kind of integration a build system like meson on top of cargo is more suitable I guess.

**Comment by ids1024** [comment]
Nevermind depending on an xml parser; `glib-compile-resources --generate-dependencies` outputs a newline separated list of dependencies.
