### ISSUE TITLE
generator.py does not rebuild gir if it changed since last build

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs#26]
After updating the `gir` submodule, `generator.py` just re-uses the previous build of it instead of first doing a new build. Removing `gir/target` works around that.

CC @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Can you list the commands you did exactly please?

**Comment by sdroege** [comment]
* `./generator.py` on a clean repo (-> builds gir first)
* Update gir submodule
* `./generator.py` (-> runs the old version from first step)
