### ISSUE TITLE
add glib::Timer bindings

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs#265]

**Comment by sdroege** [comment]
Why? `std::time::Instant` basically provides the same features :)

**Comment by bilelmoussaoui** [comment]
Ah, I didn't knew the std has something equivalent to it :) I guess we can close this one then, unless you think providing a way to convert `glib_sys::GTimer` to a `std::time::Instant` would make sense? :)

**Comment by sdroege** [comment]
They can't be converted AFAICS, but provide similar functionality. I don't think `GTimer` is exposed in any other API, so having it in the bindings wouldn't seem very useful unless you can think of something.

**Comment by bilelmoussaoui** [comment]
I don't have a usage of the API myself, I just noticed it while looking at the missing glib/gio bindings. I guess we can close this, if someone needs it we can re-open it.
