### ISSUE TITLE
Cairotest doesn't run

### ISSUE THREAD

**Issue by caseykneale** [gtk-rs/gtk-rs#276]
Not sure if it's just me, or if the cairotest.rs code is outdated?
https://github.com/gtk-rs/gtk-rs/blob/master/examples/src/bin/cairotest.rs
Errors include things like:
```crate `cairo` is private
private craterustc(E0603)
```

```error: no method named `connect_activate` found for struct `Application` in the current scope
label: method not found in `Application`
```

**Comment by caseykneale** [comment]
got it to work with the following deps:
```queues = "1.1.0"
gtk = { version = "0.9.2", features = ["v3_22"] }
cairo-rs = "0.9.1"
gio = "0.9"
gdk = "0.13"
gdk-pixbuf = "0.9.0"
```
and the following imports...
```
extern crate gtk;
use gio::prelude::*;
use gtk::prelude::*;
use cairo::{Context, FontSlant, FontWeight};
use gtk::DrawingArea;

use std::env::args;
use std::f64::consts::PI;
```

I won't close this because I don't know if what I've done is even the right thing!

**Comment by sdroege** [comment]
How can we reproduce the compiler error, step by step?

I tried from latest master of gtk-rs, running `cargo clean` and `cargo update` first, and then running `cargo run --bin cairotest` from inside the `examples` subdirectory. That worked without problems.

**Comment by caseykneale** [comment]
The issue is if you copy the file only, and then try to run the code not knowing the appropriate dependencies, you won't be able to run it. IE: don't use Cairo, use Cairo-rs, etc. So it's a "new person" problem I think... But, for new people it might help to share dependencies cleanly? For example, the *.toml file in the directory isn't explicit?

**Comment by sdroege** [comment]
The Cargo.toml in the examples is pointing at the git versions of all the crates as that's exactly the version that is needed.

I'm not sure how to improve on this for new people. Do you have a suggestion? This seems more like a documentation problem than code problem though.

**Comment by caseykneale** [comment]
I think it's a me not understanding Cargo fully yet. I think we can close this issue. I saw what looked like local directory strings, ie: "../gtk" and assumed the dep's weren't included in the project. Which is wrong!
