### ISSUE TITLE
KeyFile get_comment() doesn't allow None for key argument like set_comment() does

### ISSUE THREAD

**Issue by epakai** [gtk-rs/gtk-rs#282]
Seems like it should allow both key and group_name to be None just like set_comment.

For g_key_file_get_comment() the docs say: "If both key and group_name are NULL, then comment will be read from above the first group in the file."

**Comment by sdroege** [comment]
Indeed, do you want to provide a PR for that? This should be solveable by marking the parameter `nullable` in the `Gir.toml`.

**Comment by epakai** [comment]
Not familiar with this, but I tried to add it, and ran the generator.py script. It seemed to have the right effect.
