### ISSUE TITLE
Did we have a usercase list for list which application / library used gtk-rs ?

### ISSUE THREAD

**Issue by imiskolee** [gtk-rs/gtk-rs#283]
Hi,All: 
 I am trying to use GTK to build a small application [Signal Generator](https://github.com/imiskolee/rust-dsp-starter/tree/main/signal_generator) and looks like my code too dirty.

I just found a music player used gtk-rs, https://github.com/gmg137/netease-cloud-music-gtk

So, I am asking other user cases how to works.

**Comment by sdroege** [comment]
There's https://gtk-rs.org/#projects-using-gtk-rs
