### ISSUE TITLE
GTK TreeView: panic when using more than two columns

### ISSUE THREAD

**Issue by RomeuG** [gtk-rs/gtk-rs#285]
Hi everyone.

I hope I am not missing anything but, when trying out your simple TreeView example, if I add one more column, the program just crashes.

First off, I am using these dependencies:
```
[dependencies.gtk]
version = "0.9.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]
```

Here is a gist with the changed code: https://gist.github.com/RomeuG/b1c20a4e7bbd3c715fa1e962695bb661

The crash is this:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `3`', /home/romeu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The backtrace offers more information on the line of code this is happening:

```
13: <O as gtk::list_store::GtkListStoreExtManual>::insert_with_values
             at /home/romeu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16
14: liststore::create_and_fill_model
             at src/main.rs:21
```

Correct me if I am wrong, but can't ListStore have more than 2 columns? Is it something I am forgetting?
Thanks!

**Comment by sdroege** [comment]
```rust
        model.insert_with_values(None, &[0, 2], &[&(i as u32 + 1), &entry, &more_entries[i]]);
```

You're here inserting 3 values (the last parameter) into 2 columns (the second parameter, `&[0, 2]`). That doesn't work, you always have to provide the same number of elements for both.

Maybe that function should be changed to take a slice of tuples instead so this mistake is prevented by the API. @GuillaumeGomez @bilelmoussaoui, opinions?

**Comment by RomeuG** [comment]
Oh, wow. I get it now, I should use something like `&[0, 1, 2]`.
I will be honest I was reading `&[0, 2]` as a range of values from 0 to 2 inclusive.

I don't really know what is best in this case, so I will let you discuss it.

Thanks!

**Comment by bilelmoussaoui** [comment]
> Maybe that function should be changed to take a slice of tuples instead so this mistake is prevented by the API. @GuillaumeGomez @bilelmoussaoui, opinions?

So that you would write the code above like
 ```rust
model.insert_with_values(None, &[(0, i + 1), (1, &entry), (2, &more_entries[i])]);
```
 ? If that's the case, it looks good to me. We just need to ensure it's properly documented.

**Comment by sdroege** [comment]
Yes like that. I don't know how to document that without it causing problems with the gobject-introspection-provided docs. @GuillaumeGomez ?

**Comment by bilelmoussaoui** [comment]
`rustdoc-stripper-ignore-next` is the keyword it seems, see https://github.com/gtk-rs/gtk4-rs/blob/master/gtk4/src/dialog.rs#L44

**Comment by sdroege** [comment]
Actually the gobject-introspection docs that are already inserted for this function are describing how the new function works... because they incidentally come from the varargs variant of the function instead of the `valuesv` variant. So the docs are fine and it all works much closer to the C API now.

@bilelmoussaoui I leave backporting to GTK4 to you.
