### ISSUE TITLE
clone! macro makes error messages cryptic

### ISSUE THREAD

**Issue by Cogitri** [gtk-rs/gtk-rs#287]
Hello,

when using the `clone!` macro rustc doesn't report the line where the errror occured correctly and instead just points to the entire macro invocation. This forces users of the macro to guess where the error occured, which isn't trivial when the function `clone!` encapsulates is longer than a few lines.

E.g. when I forget to put a semicolon somewhere the error message looks like this:

```
error: expected one of `.`, `;`, `?`, or an operator, found `self_`
   --> src/widgets/sync_list_box.rs:133:40
    |
133 |                   .connect_row_activated(clone!(@weak obj => move |list_box, row| {
    |  ________________________________________^
134 | |                     let self_ = imp::HealthSyncListBox::from_instance(&obj);
135 | |                     if (row == &self_.google_fit_start_sync_row.get()) {
136 | |                         self_.google_fit_stack.set_visible(true);
...   |
180 | |                     }
181 | |                 }));
    | |__________________^ expected one of `.`, `;`, `?`, or an operator
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```

So I have to check some 50 lines to know where I forgot the semicolon.

See https://github.com/Cogitri/clone-reproducer for a reproducer:

```
error[E0599]: no method named `qiut` found for struct `gtk4::Application` in the current scope
   --> src/bin/entry_completion.rs:101:9
    |
101 | /         glib::clone!(@weak application => move |_action, _parameter| {
102 | |             application.qiut();
103 | |         }),
    | |__________^ method not found in `gtk4::Application`
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

In this case the error message seems OK because it's only a one line function, but ideally it'd point to only line 102 and not 101/103.

**Comment by sdroege** [comment]
This looks like the `clone!` macro doesn't handle spans correctly.

**Comment by sdroege** [comment]
@GuillaumeGomez Any guesses?

**Comment by GuillaumeGomez** [comment]
Not that I can see right away but I might have an idea if this is the proc-macro version.

@Cogitri Which version of glib-macro are you using? (the one from the repository I assume but just to be sure...)

**Comment by bilelmoussaoui** [comment]
The issue is with the proc-macro version yes

**Comment by GuillaumeGomez** [comment]
To be exact, only this code is needed:

```rust
let application = Application::new(
    Some("whatever"),
    Default::default(),
)
.expect("Initialization failed...");
let quit = SimpleAction::new("quit", None);
quit.connect_activate(
    glib::clone!(@weak application => move |_action, _parameter| {
        application.qiut();
    }),
);
```

And considering it's a span emitted on the code generated by the proc macro, I didn't find any way to be able to provide a better one. If someone has an idea?

**Comment by GuillaumeGomez** [comment]
@antoyo suggested a way to fix this. I'll give it a try.
