### ISSUE TITLE
Add `connect_notify_local()` as equivalent of `connect_local()`

### ISSUE THREAD

**Issue by haecker-felix** [gtk-rs/gtk-rs#29]
We have `connect_local()`, but no `connect_notify_local()` (only `connect_notify()`). As discussed in Matrix it would make sense to add this too.  

A workaround that works in the meantime: `connect_local("notify::the_property_name")`.

**Comment by sdroege** [comment]
Do you want to provide a PR for that?

**Comment by haecker-felix** [comment]
Not in near future, since the `connect_local("notify::the_property_name")`-way works finely for me at the moment.

**Comment by sdroege** [comment]
Ok :man_shrugging: I'll add it in a bit then, that's about 3 lines :)

**Comment by haecker-felix** [comment]
Oh 3 lines? I expected a lot more :see_no_evil: 
I definitely have to dive into bindings stuff soon, still no idea how this magic works in detail...

**Comment by sdroege** [comment]
I'll CC you in the PR :) Going through such small PRs is probably a good start to get an idea of how things work under the hood.

**Comment by haecker-felix** [comment]
Sounds like a good idea - thanks!

**Comment by sdroege** [comment]
Was not actually 3 lines, but copy and paste and changing 2 lines ;)
