### ISSUE TITLE
gdk_gl_texture_new is not bound

### ISSUE THREAD

**Issue by elmarco** [gtk-rs/gtk-rs#295]
//#[doc(alias = "gdk_gl_texture_new")]
    //pub fn new(context: &GLContext, id: u32, width: i32, height: i32, data: /*Unimplemented*/Option<Fundamental: Pointer>) -> GLTexture {
    //    unsafe { TODO: call ffi:gdk_gl_texture_new() }
    //}

Help appreciated to fix it. Thanks!

**Comment by GuillaumeGomez** [comment]
Do you know how to use it in C? If so, do you have maybe an example so we can see if there might be any issues? In any case, it won't be possible to generate it automatically so it'll need a manual implementation which will look like this I think:

```rust
#[doc(alias = "gdk_gl_texture_new")]
pub fn new<T>(context: &GLContext, id: u32, width: i32, height: i32, data: &T) -> Option<GLTexture> {
    let ptr = unsafe { ffi:gdk_gl_texture_new(context.to_glib_full(), width, height, data as *const T as *const _) };
    if ptr.is_null() {
        None
    } else {
        Some(GLTexture(ptr))
    }
}
```

**Comment by sdroege** [comment]
It would have to be `unsafe` because it works with a OpenGL texture id. And also that `data` needs some more thoughts with regards to memory management, what you did there is not valid.

**Comment by GuillaumeGomez** [comment]
Do you have to hold the memory? I thought it was copied over to the GPU and so it wasn't needed anymore for us to ensure it lived as long as the texture...

**Comment by sdroege** [comment]
How would an arbitrary unknown type `T` be copied over to the GPU and hold there?

**Comment by GuillaumeGomez** [comment]
Oh, just realized my mistake: it needs to be a slice!

**Comment by sdroege** [comment]
No, it can be anything but it lives on the CPU side. And there's a destroy notify for managing its lifetime.

**Comment by GuillaumeGomez** [comment]
So we'll have to store it in any case, or enforce the lifetime on the type if we only keep a reference.

**Comment by elmarco** [comment]
@GuillaumeGomez I have built a texture from a dmabuf fd. I'd just need the destroy callback to eventually close the fd. data seems to be just used for the destroy callback.

@sdroege agree about unsafe.
