### ISSUE TITLE
`gdk::Window::create_similar_image_surface` `format` argument takes `i32` instead of `cairo::Format`

### ISSUE THREAD

**Issue by a33k** [gtk-rs/gtk-rs#297]
Title says it all. Compare [GTK docs](https://developer.gnome.org/gdk3/stable/gdk3-Cairo-Interaction.html#gdk-window-create-similar-image-surface) and [gtk-rs docs](https://gtk-rs.org/docs/gdk/trait.WindowExt.html#tymethod.create_similar_image_surface).

**Comment by sdroege** [comment]
It's marked wrong in the XML and in the annotations in the C code (note the `(type int)` annotation).

```xml
          <parameter name="format" transfer-ownership="none">
            <doc xml:space="preserve"
                 filename="gdk/gdkwindow.c"
                 line="10203">the format for the new surface</doc>
            <type name="gint" c:type="cairo_format_t"/>
          </parameter>
```

This ideally has to be fixed first in the annotations (by just not specifying the type at all instead of wrongly), and then by update the `Gdk-3.0.gir` file accordingly here.

**Comment by sdroege** [comment]
See https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3228
