### ISSUE TITLE
gtk::TextView: thread 'main' panicked at 'str::ToGlibPtr<*const c_char>: unexpected '' character: NulError

### ISSUE THREAD

**Issue by RomeuG** [gtk-rs/gtk-rs#298]
Hi.

I am using a TextView to show a string which has non-ascii information.
The string was generated through `String::from_utf8_lossy()` and afterwards put into a textview. This is the code:

```
let a = std::string::String::from_utf8_lossy(&saz[computed_index].file_request_contents.as_bytes());
let b = std::string::String::from_utf8_lossy(&saz[computed_index].file_response_contents.as_bytes());

dbg!(&b);

requestTextView.get_buffer().unwrap().set_text(&a);
responseTextView.get_buffer().unwrap().set_text(&b);
```

But, unfortunately, I get a panic:

```
thread 'main' panicked at 'str::ToGlibPtr<*const c_char>: unexpected '' character: NulError(604, [72, 84,...])', /home/romeu/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.10.3/src/translate.rs:379:32
```

I did cut the bytes from NulError, there is a lot of information.
For more information, please check this Gist I created: https://gist.github.com/RomeuG/e3778d8ab203ea7c12affcbb8a89fb97

Maybe it is something that I am missing, but all I want to do is to show a string that includes many non-ascii bytes in a readable format inside a TextView.

Am I in the correct path, or am I donig something wrong?

Thanks.

**Comment by sdroege** [comment]
Your string contains `\0` characters, which is not allowed for C strings and would cause the string to be cut off at that character when being displayed in a text view (or anywhere else).

**Comment by RomeuG** [comment]
I see. The problem is obvious and it makes total sense.

But then again, how would I go about showing that text in a textview? As an example, Fiddler captures bytes and shows them like this:

![image](https://user-images.githubusercontent.com/2325589/107560101-d83c4780-6bd4-11eb-93fd-79144d1db3e7.png)

What could I do to get the same results?

**Comment by sdroege** [comment]
You would replace the `\0` characters with some replacement character before passing it to GTK.

**Comment by RomeuG** [comment]
I see, thank you!
