### ISSUE TITLE
MainContext::pending & iteration are missing

### ISSUE THREAD

**Issue by jpercyasnet** [gtk-rs/gtk-rs#303]
According to the gtk4 migration gtk_event_pending has been replaced with g_main_context_pending. However, the compiler told me to use 
use gtk::glib_sys::ffi::g_main_context_pending;.
However g_main_context_pending documentation states it is boolean, but when I tried compiling it, expects a i32.
I am trying to replace this code:
 while gtk::events_pending() {
      gtk::main_iteration_do(true);
 }
But no one seems to give examples on how to use the g_main_context_pending and g_main_context_iteration()

**Comment by sdroege** [comment]
There's not actually anything missing here from what I can see. There's [`glib::MainContext::iteration`](https://gtk-rs.org/docs/glib/struct.MainContext.html#method.iteration) and [`glib::MainContext::pending`](https://gtk-rs.org/docs/glib/struct.MainContext.html#method.pending).
