### ISSUE TITLE
Crash while calling gio::File::load_contents() on a gresource

### ISSUE THREAD

**Issue by bellegarde-c** [gtk-rs/gtk-rs#305]
Calling gio::File::load_contents() on a resource:// URI segfaults.

Reproducer: https://github.com/bellegarde-c/gtk4-rs-gio-file-loads-content-crash

Crash is in: https://github.com/bellegarde-c/gtk4-rs-gio-file-loads-content-crash/blob/master/src/application.rs -> fn setup_css() after println!()

backtrace: 
[gdb.txt](https://github.com/gtk-rs/gtk4-rs/files/5990615/gdb.txt)

**Comment by sdroege** [comment]
The `etag` out parameter of `g_file_load_contents()` needs to be nullable apparently, but isn't. Unclear if that's a bug in gio (maybe it must never be `NULL` and that's the problem here), or just an annotation problem (it's valid to be `NULL`).

Will check in more detail tomorrow.

**Comment by sdroege** [comment]
See https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1956 . The annotations were simply missing.

**Comment by bellegarde-c** [comment]
Thanks, will use load_bytes() until the fix is in org.gnome.Sdk//master.
