### ISSUE TITLE
Missing expose-event on WidgetExt

### ISSUE THREAD

**Issue by wusyong** [gtk-rs/gtk-rs#309]
I was looking for an equivalent method to connect "expose-event" signal but couldn't find it.
Is It able to open a PR to add this option?

**Comment by sdroege** [comment]
Which `expose-event` signal do you mean? There doesn't seem to be anything like that on `GtkWidget`.

There's the expose `GdkEvent` though, you could get that (and others) via the `event` signal on `GtkWidget`.

**Comment by wusyong** [comment]
I'm trying to make a transparent window and the posts ([1](https://gist.github.com/mertyildiran/e83fc3091b355280ada63534432adcea#file-alphademo-c-L53), [2](https://stackoverflow.com/questions/3908565/how-to-make-gtk-window-background-transparent)) I found all require this signal.
I searched the doc after this and seems like there's [`Event::send_handler`](http://gtk-rs.org/docs/gdk/struct.Event.html#method.set_handler). Does it do a similar job?

**Comment by sdroege** [comment]
>  I'm trying to make a transparent window and the posts ([1](https://gist.github.com/mertyildiran/e83fc3091b355280ada63534432adcea#file-alphademo-c-L53), [2](https://stackoverflow.com/questions/3908565/how-to-make-gtk-window-background-transparent)) I found all require this signal.

That looks like GTK2. There an `expose-event` on `GtkWidget` existed.

I don't know how to do this with GTK3/4, you'd have to ask someone who knows GTK. Maybe @bilelmoussaoui knows?

Apart from that, this should really be asked on the GNOME discord as it's not really something missing/wrong in the bindings but a general GTK question: https://discourse.gnome.org

**Comment by bilelmoussaoui** [comment]
In gtk4 it's pretty easy, there's an "Empty" theme shipped by default which is "almost" completely transparent. No idea about gtk3 though
