### ISSUE TITLE
Magic proc macro to simplify implementing ObjectSubclass

### ISSUE THREAD

**Issue by ids1024** [gtk-rs/gtk-rs#322]
Implementing `ObjectSubclass` is rather verbose. In fact more so than with the previous release due to the addition of `Type` and `Interfaces`:

```rust
impl ObjectSubclass for FooBarInner {
    const NAME: &'static str = "FooBar";

    type ParentType = gtk::Widget;
    type Type = FooBar;
    type Interfaces = ();

    type Instance = subclass::simple::InstanceStruct<Self>;
    type Class = subclass::simple::ClassStruct<Self>;

    glib::object_subclass!();

    fn new() -> Self {
        Self::default()
    }
}
```

There are a few annoying things there that seem unnecessary, but there's no way to handle them better in standard Rust (yet):
* `Interfaces`, `Instance`, and `Class` should use associated type defaults, but that isn't stable.
* Calling `glib::object_subclass!();` here is annoying, but there's no way in Rust to associate static data with instances of a trait.
* Recently it was suggested on IRC that `new()` should default to `Default::default()`, but there's no way to do that without requiring a `Default` bound for all `ObjectSubclass` implementations.

Perhaps a magic proc macro could handle of of this:

```rust
#[glib::object_subclass]
impl ObjectSubclass for FooBarInner {
    const NAME: &'static str = "FooBar";
    type ParentType = gtk::Widget;
    type Type = FooBar;
}
```

This seems a lot neater, and is sufficient for most cases where I've implemented `ObjectSubclass`. It would still allow custom values of the associated type, or custom `new()`.

**Comment by sdroege** [comment]
That seems useful, yes. A workaround for the missing language features :)

**Comment by ids1024** [comment]
Closing now that https://github.com/gtk-rs/gtk-rs/pull/335 is merged.
