### ISSUE TITLE
Improve default interface method handling

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs#328]
GObject allows an interface to be implemented by multiple types in the class hierarchy, e.g. `GtkApplication` and `GApplication` could both implement `GActionGroup`. When calling the methods, the most bottom type has priority.

Now when implementing e.g. `GActionGroup` on `MyApplication`, which inherits from `GtkApplication`, one might not want to implement the `ActionGroupImpl::action_added` method. Right now the code looks as follows

```rust
pub trait ActionGroupImpl: ObjectImpl {
    fn action_added(&self, action_group: &Self::Type, action_name: &str) {
        unsafe {
            let type_ = ffi::g_action_group_get_type();
            let iface = glib::gobject_ffi::g_type_default_interface_ref(type_)
                as *mut ffi::GActionGroupInterface;
            assert!(!iface.is_null());

            if let Some(f) = (*iface).action_added.as_ref() {
                f(
                    action_group
                        .unsafe_cast_ref::<ActionGroup>()
                        .to_glib_none()
                        .0,
                    action_name.to_glib_none().0,
                );
            }

            glib::gobject_ffi::g_type_default_interface_unref(iface as glib::ffi::gpointer);
        }
    }
}
```

This would now call the default implementations of `GActionMap` but not the implementation of `GtkApplication` or `GApplication`.

We can get the correct one via `g_type_interface_peek_parent()` but that will return `NULL` if the parent type does not implement the interface so there would also have to be a fallback to `g_type_default_interface_peek()`.

Always calling both is a bit wasteful, so ideally we would retrieve this once during type registration and keep the interface vtable around somewhere inside the `ObjectSubclass::type_data`.

----

Also the above code wouldn't have to call `ref()` and `unref()` but just `peek()` is sufficient because the interface must be around anyway if we have an instance. But once implementing what I wrote above this wouldn't be necessary anymore anyway.

CC @BrainBlasted, who looked into this a while ago AFAIU.

**Comment by sdroege** [comment]
An implementationof that for `gst::ChildProxy` can be found here: https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/merge_requests/712

Opinions @bilelmoussaoui @BrainBlasted @ids1024 ?

**Comment by bilelmoussaoui** [comment]
Aha, I somehow completely missed the chaining up part. 

>  We can get the correct one via g_type_interface_peek_parent() but that will return NULL if the parent type does not implement the interface so there would also have to be a fallback to g_type_default_interface_peek().

Can we have some kind of helper for this here in glib?

**Comment by sdroege** [comment]
> Can we have some kind of helper for this here in glib?

Note that I didn't use any of that API because... the only entry-point we have is the `interface_init` and calling any of those functions will deadlock from in there because the `GType` mutex is locked :)

So instead I just copy the interface vtable and keep it around, which is a one-liner.

For a helper, I'm not sure what to do there. Interfaces that already use the `TypeData` for themselves will need to store it in a custom way anyway because there's not yet another slot for them in the `TypeData`.

What do you suggest, based on the GStreamer MR? Go ahead with this and do that for the 5 or so interfaces with default methods that we have?

----

Also as I just noticed: we need to provide callers for the default/parent implementation for *all* interface methods. Not just the ones that have a default implementation. A parent class might implement the interface regardless and we possibly would have to chain up.

So something like this will have to be done for all interfaces and all interface methods. I would keep the `InterfaceImpl` traits as they are though and make all methods that don't have a default impl mandatory to implement.

What do you think?

**Comment by sdroege** [comment]
@bilelmoussaoui ? :)

**Comment by bilelmoussaoui** [comment]
> For a helper, I'm not sure what to do there. Interfaces that already use the `TypeData` for themselves will need to store it in a custom way anyway because there's not yet another slot for them in the `TypeData`.

Maybe we can add  a `parent_iface` to `TypeData` to automate/simplify part of the interface implementation code.

> What do you suggest, based on the GStreamer MR? Go ahead with this and do that for the 5 or so interfaces with default methods that we have?

Looks good to me, we have a bunch of interfaces in gtk4-rs, I will have to look at which ones provide a default method for those as well. But overall it shouldn't be a lot of work. 

> Also as I just noticed: we need to provide callers for the default/parent implementation for _all_ interface methods. Not just the ones that have a default implementation. A parent class might implement the interface regardless and we possibly would have to chain up.

I guess that's fine, we already do that for objects
