### ISSUE TITLE
Change locale directory

### ISSUE THREAD

**Issue by fabi321** [gtk-rs/gtk-rs#330]
I want to use a custom locale directory, and as far as I found out, it's possible to give a builder a translation_domain, but I didn't found any way to pass over a directory as wanted by the underlying c command:
`char * bindtextdomain (const char * domainname, const char * dirname);`
I'm using a glade file so I don't know any other way than the Builder.
I'm currently using `builder.set_translation_domain(Some("app_name"));`.
My target is to use locales in a po directory in the project root.

**Comment by bilelmoussaoui** [comment]
You should use gettext-rs.

**Comment by fabi321** [comment]
How to use gttext-rs with a builder file?

**Comment by bilelmoussaoui** [comment]
You can't use it? what you're trying to achieve isn't possible with a UI file. The ui file is about constructing widgets/objects. See gettext-rs's docs https://docs.rs/gettext-rs/0.5.0/gettextrs/ on how to use it.

**Comment by fabi321** [comment]
If I put my language file to `/usr/share/locale-langpack/de/LC_MESSAGES/messages.mo`, it works fine, but this is not a very portable solution

**Comment by sdroege** [comment]
This seems more like a support request than an issue in the bindings. Please ask this on the [GNOME discourse](https://discourse.gnome.org), thanks!
