### ISSUE TITLE
gtk::StyleContextExt::get_background_color deprecated.

### ISSUE THREAD

**Issue by Aurailus** [gtk-rs/gtk-rs#332]
Hi! First, I'd just like to say that I've been using gtk-rs for a few weeks now and I love how straightforward it is to use. Thank you!

Now, my issue: `gtk::StyleContextExt::get_background_color` and `gtk::StyleContextExt::get_border_color` are deprecated. The deprecation warning posits that the only use for these functions is rendering the context's widget. This is incorrect. I'm developing an application where I need to use colors for certain elements that are derivative of other theme colors, and the only way I've found to get arbitrary theme colors in the code is to use these functions. Rendering the component doesn't solve my issue, as I'm trying to style an entirely separate component. Below is a snippet of my code where I use these deprecated functions.

```
pub fn style(window: &gtk::ApplicationWindow) {
	let provider = gtk::CssProvider::new();

	let mut s = String::new();

	let mut add_color = |identifier: &str, color: &gdk::RGBA| {
		s.push_str("@define-color ");
		s.push_str(identifier);
		s.push_str(" ");
		s.push_str(colorsys::Rgb::new(color.red * 255.0, color.green * 255.0, color.blue * 255.0, None).to_css_string().as_str());
		s.push_str(";\n");
	};

	let button = gtk::Button::new();
	add_color("scale_color", &button.get_style_context().get_background_color(gtk::StateFlags::ACTIVE));
	add_color("background_color", &window.get_style_context().get_background_color(gtk::StateFlags::NORMAL));
	add_color("foreground_color", &button.get_style_context().get_color(gtk::StateFlags::NORMAL));

	let style = include_str!("./style.css");
	s.push_str(style);

	provider.load_from_data(s.as_bytes()).expect("Failed to load CSS.");
	gtk::StyleContext::add_provider_for_screen(&gdk::Screen::get_default().expect("Error initializing GTK CSS provider."),
		&provider, gtk::STYLE_PROVIDER_PRIORITY_APPLICATION);
}
```

I hope that this shows that rendering is not the only use case for these functions. Would it be possible to have the deprecation warnings removed? Otherwise, I'd appreciate an explanation of how to implement the code above without those methods.

**Comment by ids1024** [comment]
This isn't really an issue in gtk-rs, since the function is [deprecated in gtk](https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#gtk-style-context-get-background-color) and seems to be removed [in gtk4](https://developer.gnome.org/gtk4/stable/GtkStyleContext.html).

Though I'd also be interested to know what non-deprecated solution there is for such use cases.

**Comment by sdroege** [comment]
The best place to ask this would be the [GNOME discourse](https://discourse.gnome.org). I'll close this for now here until there's some action needed for the bindings.
