### ISSUE TITLE
glib::timeout_add_local accept FnOnce

### ISSUE THREAD

**Issue by piegamesde** [gtk-rs/gtk-rs#341]
I sometimes find myself in the situation of adding a timeout/callback that will be called exactly once. But the respective `glib` methods accept a `FnMut` at best. One could wrap a `FnOnce` like this and expose this as an alternative (untested code):

```rust
fn wrap_once_local(func: F) -> impl (FnMut() -> Continue + 'static)
where
    F: FnOnce() 'static,  
{
    let mut func = Some(func);
    move || {
        func.take().unwrap();
        Continue(false)
    }
}
```

**Comment by sdroege** [comment]
That's basically what https://gtk-rs.org/docs/glib/fn.timeout_future.html does, but having callback variants for these is probably also useful.

**Comment by sdroege** [comment]
Do you want to work on this?

**Comment by piegamesde** [comment]
Sure, why not. How should I implement this? I could duplicate all existing functions with a `_once` version, or I could make a generic `once` adapter.

**Comment by sdroege** [comment]
I would implement new `_once()` functions for these. The goal is to make it easy to use for the user :)

Note that there are also the `_local()` variants of the functions that should probably get a `_once()` variant too.

Internally you could use some kind of adapter if that makes anything easier for you, or duplicate the functions. Either way it's not a lot of code.

**Comment by piegamesde** [comment]
Shall I also do the `idle_add` family of functions, or only the `timeout` ones?

**Comment by sdroege** [comment]
Probably makes sense for all of them

**Comment by piegamesde** [comment]
Does it make sense for the `_source_`s as well? I never used them, and don't know if one would want to pass an `FnOnce` into them.

**Comment by sdroege** [comment]
> Does it make sense for the `_source_`s as well? I never used them, and don't know if one would want to pass an `FnOnce` into them.

Probably not, those are very specialized and whoever needs them will surely be able to figure out how to do that themselves.
