### ISSUE TITLE
Add bindings for ListStore::splice() for batch addition/removal

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs#347]
CC @bilelmoussaoui

**Comment by bilelmoussaoui** [comment]
Aha, I wasn't aware such function exists.

**Comment by bilelmoussaoui** [comment]
Actually it does exists already https://github.com/gtk-rs/gtk-rs/blob/fb8ab3c795a9ebef629350998e197f052486659f/gio/src/auto/list_store.rs#L106

**Comment by sdroege** [comment]
Oh, how did I miss that!
