### ISSUE TITLE
Add support for async blocks to the clone! macro

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs#356]
CC @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I have questions: is there anything async specific that needs to be added?

**Comment by sdroege** [comment]
No, it just has to be handled the same as for closures. Currently the macro only doesn't work because it's checking for the `|...|` :)

**Comment by GuillaumeGomez** [comment]
Yes and it's voluntary. Anyway, gonna do that in the next days then.

**Comment by sdroege** [comment]
The cases you need to handle are btw:

```rust
async { stuff }
async move { stuff }
async || { stuff } // nightly
async move || { stuff } // nightly
|| async { stuff }
move || async { stuff }
|| async move { stuff }
move || async move { stuff }
```

The handling of `move` should be done the same as the macro already does it now for closures.

**Comment by GuillaumeGomez** [comment]
So after talking about with @sdroege, it seems only following cases should be implemented:

```rust
async move {}
move |...| async move {}
async move |...| {}
```
