### ISSUE TITLE
Add support for refcounted types to GBoxed derive macro or add a new macro

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs#357]
CC @pbor

**Comment by sdroege** [comment]
CC @elmarco

**Comment by pbor** [comment]
CC @mbiggio

Initial WIP was here: https://github.com/mbiggio/gtk-rs/commits/wip/biggio/shared-types

Also adding some notes from the chat:

1. we are ok with the `SharedType` name (this mirrors the presence of `Boxed` and `Shared` in the `glib_wrapper` macro)
2. we are not sure whether we should have a new derive macro or extend `#[derive(GBoxed)]`
  * A new macro keeps things easier
  * Extending the existing one makes it more clear that we are still registering a `GBoxed` from the gtype point of view

**Comment by sdroege** [comment]
Ideally the derive macro would be able to handle `struct Foo(Rc<_>)` and `struct Foo(Arc<_>)` so that the user doesn't have to implement another trait themselves.
