### ISSUE TITLE
`drag-motion` signal handler return value should be `bool`, not `Inhibit`

### ISSUE THREAD

**Issue by SolraBizna** [gtk-rs/gtk-rs#358]
`WidgetExt::connect_drag_motion` accepts a function returning `Inhibit`, because the `drag-motion` signal handler returns a boolean. It was probably assumed that this signal's boolean returned value is used to inhibit signal propagation, like most other boolean-returning signals. However, this is not the case.

From the documentation for the D binding (which puts it more clearly than any other documentation I was able to find):

> The `::drag-motion` signal is emitted on the drop site when the user moves the cursor over the widget during a drag. The signal handler must determine whether the cursor position is in a drop zone or not. If it is not in a drop zone, it returns `FALSE` and no further processing is necessary. Otherwise, the handler returns `TRUE`. In this case, the handler is responsible for providing the necessary information for displaying feedback to the user, by calling `gdk_drag_status()`.

I can confirm that, with the current state of `gtk-rs`, returning `Inhibit(true)` results in drag acceptance, and `Inhibit(false)` results in drag rejection.

**Comment by SolraBizna** [comment]
The same thing also applies to the `drag-drop` signal. `true` → "the drop is succeeding", `false` → "the drop is failing".

**Comment by sdroege** [comment]
The same probably also applies to GTK4 in one way or another (CC @bilelmoussaoui).

@SolraBizna, do you want to submit a PR for changing this to a `bool`?

**Comment by bilelmoussaoui** [comment]
> The same probably also applies to GTK4 in one way or another (CC @bilelmoussaoui).

There are probably some functions where it's needed for GTK 4, but not those as they were removed/replaced

**Comment by SolraBizna** [comment]
As @sdroege suggested, I've made a PR that would resolve this issue. Hopefully it's adequate. I wasn't able to test it, but the changes are pretty trivial and everything does build.
