### ISSUE TITLE
clone! macro does not work with async blocks

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk-rs#369]
The content of the async block is not retained by the clone! macro.

Minimal example:
This
```rust
button.connect_clicked(move |button| {
        let main_context = MainContext::default();
        // The main loop executes the asynchronous block
        main_context.spawn_local(glib::clone!(@strong button => async move {
            // Deactivate the button until the operation is done
            button.set_sensitive(false);
            timeout_future_seconds(10).await;
            // Activate the button again
            button.set_sensitive(true);
        }));
    });
```
expands to this
```rust
  button.connect_clicked(move |button| {
        let main_context = MainContext::default();
        main_context.spawn_local({
            let button = button.clone();
            async move { {} }
        });
    });
```

**Comment by sdroege** [comment]
CC @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Oh, that's funny. Wonder how I'll test this one...

**Comment by Hofer-Julian** [comment]
> Oh, that's funny. Wonder how I'll test this one...

What do you mean? :)

Reproducing or adding tests as soon as it is fixed?

**Comment by GuillaumeGomez** [comment]
We have tests to ensure that it's doing as expected. Meaning I didn't check if the async code was actually being run (which is bad).

**Comment by GuillaumeGomez** [comment]
Don't worry, I'll find something. Finishing something else first.

**Comment by sdroege** [comment]
glib depends on `futures-executor`, so just use [`futures::executor::block_on`](https://docs.rs/futures/0.3.13/futures/executor/fn.block_on.html)... or just use the GLib main context, which is also a futures executor ;)

Just like with closures, check if the whole thing then evaluates to the expected return value (and also do it for closures).

**Comment by GuillaumeGomez** [comment]
That's exactly what I was looking for, thanks!
