### ISSUE TITLE
Pango LayoutLine::x_to_index doesn't report offset when x is outside of line

### ISSUE THREAD

**Issue by cmyr** [gtk-rs/gtk-rs#374]
The C signature or this function is,

```c
gboolean
pango_layout_line_x_to_index (PangoLayoutLine *line,
                              int x_pos,
                              int *index_,
                              int *trailing);
```

Importantly, it 'returns' three values; `index`, `trailing`, and a `bool` indicating whether or not `x_pos` is within the horizontal bounds of the line.

The signature in the `pango` crate is,

```rust
pub fn x_to_index(&self, x_pos: i32) -> Option<(i32, i32)>;
```

In this case, the `Some` case represents an `x_pos` that is inside the line's horizontal bounds, and `None` represents outside.

My understanding is is that even in the case that the hit is outside, we may still want to know what the resulting offset is, and with the current signature, that information is discarded.

I can think of two reasonable alternatives:

```rust
pub fn x_to_index(&self, x_pos: i32) -> (bool, i32, i32);
//or
pub fn x_to_index(&self, x_pos: i32) -> Result<(i32, i32), (i32, i32)>;
```

I think realistically the first option makes the most sense. I would probably also return some `Position` type with named fields instead of a tuple, but that's a personal design preference.

If you agree that this is an issue I would be happy to prepare a patch.

**Comment by GuillaumeGomez** [comment]
Oh I see. Well, in this case, using a `Result` would be incorrect since the value is valid in both cases. Here is what I suggest:

```rust
struct HitPosition {
    index: i32,
    trailing: i32,
}

enum HitStatus {
    Inside(HitPosition),
    Outside(HitPosition),
}

pub fn x_to_index(&self, x_pos: i32) -> HitStatus;
```

Does that seem correct to you? I added "hit" in the naming each time so that it doesn't conflict with other types (`Position` seems too "general" as is). If it's ok, a PR would be very welcome. :)

**Comment by cmyr** [comment]
My thinking of `Result` was matching the behaviour of the various `binary_search` methods in `std`, where the `Error` case is still useful, but conveys that an item is  not in the collection; this feels analogous?

I would suggest just,

```rust
struct HitPosition {
    index: i32,
    trailing: i32,
    is_inside: bool,
}

pub fn x_to_index(&self, x_pos: i32) -> HitStatus;
```

This feels maximally explicit, and is a good translation of the original API. The reason I prefer not to return an enum is that you will often want to take the same code path regardless of whether the hit is inside or not, and an enum complicates that without providing much real benefit.

**Comment by GuillaumeGomez** [comment]
You can easily discard the `is_inside` which I thought we wanted to avoid but you might be right, maybe I'm just overthinking things... Well, your solution works too so waiting for your PR then!

**Comment by cmyr** [comment]
Looking into it now. Are there any special rules about editing in `pango/src/auto`? If I'm adding this `HitPosition` struct, should that live elsewhere?

**Comment by GuillaumeGomez** [comment]
You have to move the function implementation outside of `auto` inside `src`. Look at how we do for other types. You'll also need to tell `gir` to ignore this function in `Gir.toml`.

**Comment by cmyr** [comment]
great, thanks!
