### ISSUE TITLE
Should Win32 streams use AsRawHandle rather than IntoRawHandle?

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/gtk-rs#381]
Warning: I don't know what I'm doing, I just ran into this while implementing librsvg's stdin/stdout for win32.

Gtk-rs has these:

```rust
impl Win32InputStream {
    pub unsafe fn new<T: IntoRawHandle>(handle: T) -> Win32InputStream { ... }
}

impl Win32OutputStream {
    pub unsafe fn new<T: IntoRawHandle>(handle: T) -> Win32OutputStream { ... }
}
```

However, `std::io::stdin()` implements `AsRawHandle`, not `IntoRawHandle`.  The latter is only for `ChildStdin`, which is from `std::process::Child`.  Stdout is analogous.

I think gtk-rs may want `T: AsRawHandle` in the `new()` functions, but I haven't had a chance to actually try to compile code like this on Windows:

```
    pub fn stream() -> InputStream {
        let stream = unsafe { Win32InputStream::new(io::stdin().as_raw_handle()) };
        stream.upcast::<InputStream>()
    }
```

**Comment by federicomenaquintero** [comment]
Sort of proof here - https://github.com/gtk-rs/gtk-rs/pull/382/checks?check_run_id=2180023075

**Comment by pbor** [comment]
Mmm... this is the same as `UnixInputStream` that takes a `IntoRawFd`. In both cases the pass `true` to the underlying `close` flag so they are taking ownership of the fd/handle.

Maybe the right thing to do while we are still in time is to have two constructors (eg _new and _take), one that takes ownership and one that does not. This would be functionally equivalent to the glib API which takes the close param.

**Comment by sdroege** [comment]
I think that would be the correct approach here, also for the UNIX variant. @pbor you make a PR?

**Comment by pbor** [comment]
Using _new() and _take() is problematic because _new() would change semantic and silently broke existing code.

I will go with adding _without_close() variant of the constructor, but if anyone has better ideas on naming, I would love to hear them :)

**Comment by pbor** [comment]
On irc/matrix we decided to go with take_fd and with_fd
