### ISSUE TITLE
glib: Auto conversion of property and signal names

### ISSUE THREAD

**Issue by mehmooda** [gtk-rs/gtk-rs#409]
Currently if you define a property in your ObjectImpl with an underscored name:
```rust
glib::ParamSpec::boolean(
    "underscored_name",
    "underscored_name",
    "underscored_name",
    true,
    glib::ParamFlags::READWRITE,
)
```
It is silently converted into underscored-name (with a hyphen[|dash|minus]).

If you try to use the property:
```rust
glib::Object::new(&[("underscored_name",&false)])
```
This results in an error when you try to use the property of `Can't find property "underscored_name"`

We should be consistent in applying the auto-conversion of property signal names.

I suggest disallowing the creation of invalid property/signal names in the ObjectImpl rather than applying auto-conversion in the rest of the API.

**Comment by sdroege** [comment]
The paramspec and signal constructors should check for valid names and panic otherwise. What is a valid name can be based on the code inside GLib.

**Comment by bilelmoussaoui** [comment]
The fix should also add a comment to the docs about the requirement for the property names
