### ISSUE TITLE
Debug impl for Value is misleading

### ISSUE THREAD

**Issue by jplatte** [gtk-rs/gtk-rs#417]
Example of the `Debug` output for a `SendValue` containing a `guint`:

```rust
SendValue(Value(GString(Foreign(0x7f6c008620, 24))))
```

This is the [Debug impl](https://docs.rs/glib/0.10.3/src/glib/value.rs.html#300-309):

```rust
impl fmt::Debug for Value {
    fn fmt(&self, f: &mut fmt::Formatter) -> Result<(), fmt::Error> {
        unsafe {
            let s: GString =
                from_glib_full(gobject_sys::g_strdup_value_contents(self.to_glib_none().0));

            f.debug_tuple("Value").field(&s).finish()
        }
    }
}
```

I don't know what it does exactly, but it looks like it always outputs a string for some reason. Also, IMHO the `SendValue()` and `Value()` wrapping in the output is not very useful.

What I'd love to see instead: `guint(10)` for both a `Value` and `SendValue`.

There is precedent for not only printing inner values in the standard library: [NonZero*](https://doc.rust-lang.org/src/core/num/nonzero.rs.html#11-23), [Rc](https://doc.rust-lang.org/src/alloc/rc.rs.html#1633-1637), even [Cow](https://doc.rust-lang.org/src/alloc/borrow.rs.html#377-387).

**Comment by sdroege** [comment]
> ```rust
>             f.debug_tuple("Value").field(&s.as_str()).finish()
> ```

This would be more correct and actually print the type :) Want to send a PR?

Making this `guint(10)` will be non-trivial, just printing the type properly would be what that code intended.

**Comment by jplatte** [comment]
Sure, I can send a PR. How do you feel about removing the `SendValue` and `Value` newtypes from the debug output (writing only `s.as_str()`)?

**Comment by sdroege** [comment]
If we were able to print the value itself, yes. But we can only really print the type so I'd go with `SendValue(TYPE)` and `Value(TYPE)` (i.e. not `SendValue(Value(TYPE))`).
