### ISSUE TITLE
ParamSpec trait should be unsafe

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs#430]
See https://github.com/gtk-rs/gtk-rs/pull/400#discussion_r605392775

**Comment by sdroege** [comment]
Maybe also other traits, like the cairo pattern one.

**Comment by pbor** [comment]
I do not see any pattern trait in cairo...

**Comment by sdroege** [comment]
Indeed, that's solved differently nowadays. `gdk::FromEvent` is another one though. I think that's all :)
