### ISSUE TITLE
Consider posibility of eliminating need for a glib_object_subclass! macro

### ISSUE THREAD

**Issue by ids1024** [gtk-rs/gtk-rs#44]
It isn't too bad, but it's a bit awkward to have magic macros defining methods like this. It seems `type_data()` and `get_type()` should just have default implementations (are there at reasons to define them any way other than what this macro does?).

As I understand it, the main reason these are defined in a macro is since each type has it's own static variable. It seems it may be possible to do some magic with [`std::any::TypeId`](https://doc.rust-lang.org/std/any/struct.TypeId.html) and a `HashMap`:

```rust
fn type_data() -> ptr::NonNull<TypeData> {
    lazy_static! {
        static ref DATAS: Mutex<HashMap<TypeId, TypeData>> = Mutex::new(HashMap::new());
    };
    let mut datas = DATAS.lock().unwrap();
    let data = datas.entry(TypeId::of::<Self>()).or_insert(TypeData {
        type_: Type::Invalid,
        parent_class: ptr::null_mut(),
        interface_data: ptr::null_mut(),
        private_offset: 0,
    });

    unsafe { ptr::NonNull::new_unchecked(data) }
}
```

```rust
fn get_type() -> Type {
    lazy_static! {
        static ref ONCE: Mutex<HashMap<TypeId, ()>> = Mutex::new(HashMap::new());
    };
    let mut once = ONCE.lock().unwrap();
    once.entry(TypeId::of::<Self>()).or_insert_with(|| {
        register_type::<Self>();
    });

    unsafe {
        let data = Self::type_data();
        let type_ = data.as_ref().get_type();
        assert_ne!(type_, Type::Invalid);

        type_
    }
}
```

The performance overhead of this over the current method probably isn't significant.

Currently this doesn't quite compile because the trait bounds required for `register_type()` are not met.

Not sure if something like this is a good idea, but it's perhaps worth thinking about.

**Comment by sdroege** [comment]
I guess this can be closed now
