### ISSUE TITLE
cairo: how to create a surface with pre-allocated buffer?

### ISSUE THREAD

**Issue by nagisa** [gtk-rs/gtk-rs#453]
It seems like there isn't a way to create a Cairo surface that points to an existing slice of memory, (underlying API: `cairo_image_surface_create_for_data`). Is there another way to approach this that I'm missing or a fundamental reason why this cannot be done?

**Comment by nagisa** [comment]
Ah, never mind, was looking at `cairo::Surface`, not `cairo::ImageSurface` that I should've been.

**Comment by nagisa** [comment]
I'm reopening this issue, because `cairo::ImageSurface::create_for_data` is not actually usable in many situations as the API is constructed today. In particular, the API looks like this:

```rust
pub fn cairo::ImageSurface::create_for_data<D: AsMut<[u8]> + 'static>(
    data: D,
    format: Format,
    width: i32,
    height: i32,
    stride: i32
) -> Result<ImageSurface, Error> { ... }
```

The `'static` bound here makes this API almost useless – there are very few ways in Rust to obtain a slice buffer that's `'static`. Two that come immediately to mind are `Vec::leak` and a global `static mut` array.

Situations where people will want to use this kind of API will instead be mostly with non-`'static` buffers, where they have an allocated buffer used or provided by some other component and they want to draw a shape or some text on top of it.

Right now the API forces the user to create a new transparent `ImageSurface`, draw the shapes and whatnot, and blend the resulting surface into the original buffer.

**Comment by sdroege** [comment]
> The 'static bound here makes this API almost useless – there are very few ways in Rust to obtain a slice buffer that's 'static. Two that come immediately to mind are Vec::leak and a global static mut array.

That's not true. `Vec<u8>`, `Box<[u8]>`, `bytes::BytesMut`, etc. are all also `AsMut<[u8]> + 'static`.

Take a look at the [cairo_threads](https://github.com/gtk-rs/gtk-rs/blob/master/examples/cairo_threads/image/image_holder.rs) example for how to solve this problem safely.

Alternatively you can also use [`ImageSurface::create_for_data_unsafe`](https://gtk-rs.org/gtk-rs/git/docs/cairo/struct.ImageSurface.html#method.create_for_data_unsafe) if you know what you're doing and your data is not actually `'static` :)

**Comment by sdroege** [comment]
@nagisa Does that answer your questions?

**Comment by nagisa** [comment]
So, `create_for_data_unsafe` is good, but is not available in the current release, which is why I missed it. Image holder or something similar is cool too.

**Comment by sdroege** [comment]
ok :)
