### ISSUE TITLE
Make !Send Value types Sendable 🚀

### ISSUE THREAD

**Issue by mehmooda** [gtk-rs/gtk-rs#456]
Currently all GTK types are `!Send` as they should only be used on the 'main' thread.

We should allow the types to be moved from thread to thread as long as they are only used on the 'main' thread. 

We could create a wrapper type: `struct NonSendValue(*mut T, MainContext)`. Which wraps a Object such as `gtk::Window` takes a reference to the `MainContext` and then only allows you to unwrap the contained value if `MainContext::is_owner` is true.

Prior art: [send_wrapper](https://crates.io/crates/send_wrapper)

**Comment by sdroege** [comment]
That already exists and is even used by these crates in various places: [fragile](https://docs.rs/fragile/1.0.0/fragile/).

If this is needed there are various external crates that allow to implement it, but I don't think this should be done automatically (it adds overhead) and also not be part of gtk-rs directly as it's a) rarely needed in proper application designs, and b) easily can lead to panics if misused.

The correct way of dealing with this in 99% of the cases is to keep things in the same thread and designing your application around that, e.g. by using channels.
