### ISSUE TITLE
example using rust unstable feature

### ISSUE THREAD

**Issue by jcbritobr** [gtk-rs/gtk-rs#467]
Hello, the follow example in master is using rust unstable features

https://github.com/gtk-rs/gtk-rs/tree/master/examples/basic_subclass

It will get fail with 
```
use of unstable library feature 'once_cell'
```

**Comment by sdroege** [comment]
The examples are depending on the `once_cell` crate for this: https://github.com/gtk-rs/gtk-rs/blob/e1f7487527a462e72d2d485fb718de806bca0876/examples/Cargo.toml#L12
