### ISSUE TITLE
Unable to use `item` method from ListModel 

### ISSUE THREAD

**Issue by haecker-felix** [gtk-rs/gtk-rs#478]
error message 
```
error[E0599]: no method named `item` found for reference `&torrent_model::TrTorrentModel` in the current scope
  --> src/transmission-gobject/src/torrent_model.rs:82:18
   |
82 |             self.item(index)
   |                  ^^^^ method not found in `&torrent_model::TrTorrentModel`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `item`, perhaps you need to implement it:
           candidate #1: `gio::subclass::prelude::ListModelImpl`

```

Interesting is, that I can use other methods from ListModel like `n_items`, but not `item`

relevant code snippets: 
```
    #[glib::object_subclass]
    impl ObjectSubclass for TrTorrentModel {
        const NAME: &'static str = "TrTorrentModel";
        type ParentType = glib::Object;
        type Type = super::TrTorrentModel;
        type Interfaces = (gio::ListModel,);
    }

    impl ObjectImpl for TrTorrentModel {}

    impl ListModelImpl for TrTorrentModel {
        fn item_type(&self, _list_model: &Self::Type) -> glib::Type {
            TrTorrent::static_type()
        }
        fn n_items(&self, _list_model: &Self::Type) -> u32 {
            self.vec.borrow().len() as u32
        }
        fn item(&self, _list_model: &Self::Type, position: u32) -> Option<glib::Object> {
            self.vec
                .borrow()
                .get(position as usize)
                .map(|o| o.clone().upcast::<glib::Object>())
        }
    }
```

```
glib::wrapper! {
    pub struct TrTorrentModel(ObjectSubclass<imp::TrTorrentModel>) @implements gio::ListModel;
}
```

complete code: https://pastebin.com/gmFra9Qh

**Comment by haecker-felix** [comment]
We just noticed that this method is named `object` instead of `item`. 

https://gtk-rs.org/gtk-rs/git/docs/gio/trait.ListModelExt.html#tymethod.object

I wonder if anything can be done here, to avoid confusion?

**Comment by bilelmoussaoui** [comment]
The get_object method has a rename-to annotation to rename it to `get_item` & it seems like that got lost during the whole get removal things. See https://developer.gnome.org/gio/stable/GListModel.html#g-list-model-get-object

cc @fengalin

**Comment by fengalin** [comment]
> The `get_object` method has a rename-to annotation to rename it to `get_item`

Are you sure? I couldn't find it in the history looking at the version prior to get removal.

**Comment by bilelmoussaoui** [comment]
Wait, does that mean we don't really handle the `rename-to` annotations? :)

**Comment by fengalin** [comment]
Are you talking about "shadows" in (Gio-2.0.gir, line 45 398):

`<method name="get_object" c:identifier="g_list_model_get_object" shadows="get_item" version="2.44">`

**Comment by sdroege** [comment]
What exactly is the problem https://gtk-rs.org/gtk-rs/git/docs/gio/prelude/trait.ListModelExt.html#tymethod.object ?

**Comment by haecker-felix** [comment]
@sdroege I think 

https://gtk-rs.org/gtk-rs/git/docs/gio/subclass/prelude/trait.ListModelImpl.html#tymethod.item

should be consistent with 

https://gtk-rs.org/gtk-rs/git/docs/gio/prelude/trait.ListModelExt.html#tymethod.object

**Comment by sdroege** [comment]
Oh I see. Yes that would make sense.

**Comment by bilelmoussaoui** [comment]
> Are you talking about "shadows" in (Gio-2.0.gir, line 45 398):
> 
> `<method name="get_object" c:identifier="g_list_model_get_object" shadows="get_item" version="2.44">`

Yes, because the g_list_model_get_item isn't bindings friendly

**Comment by fengalin** [comment]
There's no match for "shadow" grepping `gir`, so I guess either we need an explicit `rename = "item"` in `Gir.toml` or fix `gir` to handle the "shadow" annotation.

**Comment by bilelmoussaoui** [comment]
I opened an issue on gir side to handle that someday in the future https://github.com/gtk-rs/gir/issues/1112
