### ISSUE TITLE
How to use Gestures?

### ISSUE THREAD

**Issue by ggtrigg** [gtk-rs/gtk-rs#480]
I'm attempting to use a Gesture (specifically GesturePan) in my app but all attempts to have the `connect_pan` callback called have failed.
In looking at the gtk3-demo C code, I reckon my code is doing the same thing, but while the gestures are being recognised in gtk3-demo, they aren't in my app.
My test code can be accessed here - https://github.com/ggtrigg/gtk_test

If anyone has any suggestions or can point out what's different it'd be much appreciated.
(I'm quite new to rust and it's been many years since I worked with Gtk.)

**Comment by sdroege** [comment]
This is not really related to the bindings directly and certainly no bug or feature request :) Please ask such questions on the [GNOME discourse](https://discourse.gnome.org/).

**Comment by ggtrigg** [comment]
Thank you.
