### ISSUE TITLE
Multiple traits with a `fn property()`: `glib::ObjectExt` and `gtk::StyleContextExt`

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk-rs#489]
This should probably be resolved by renaming the second one to `style_property()`.

Same probably applies to gtk4 too.

CC @bilelmoussaoui

**Comment by bilelmoussaoui** [comment]
That was removed from gtk4 in favour of specific APIs to get the margin/padding/color/border. It's a gtk3 issue only
