### ISSUE TITLE
gio:File::parse_name conflict

### ISSUE THREAD

**Issue by pbor** [gtk-rs/gtk-rs#502]
In C we have `get_parse_name()` and `parse_name()` constructor.

As far as I can see in rust both are called `parse_name` one must specify the trait to disambiguate

**Comment by sdroege** [comment]
The constructor should really be `from_parse_name()`. CC @fengalin @bilelmoussaoui

**Comment by pbor** [comment]
In general I would agree... but `parse` is a verb so the whole api is kind of weird.

Another possibility is to drop the getter entirely and implement `Display`.
Implementing `Display` is a good idea on its own, so in the mean time I opened https://github.com/gtk-rs/gtk-rs/pull/503

**Comment by sdroege** [comment]
In `GFile` there's a concept of a "parse name", so I wouldn't consider it as a verb here.

**Comment by fengalin** [comment]
> The constructor should really be `from_parse_name()`.

I agree, this is a `File` constructor, not a `Path` name parser.

While we're at it, we should also probably rename other constructors:

* `new_for_commandline_arg`.
* `new_for_commandline_arg_and_cwd`.
* `new_for_path`.
* `new_for_uri`.

... either to `for_*` or `from_*`. Kind of weird they didn't get caught by the [constructor auto-renaming](https://github.com/gtk-rs/gir/blob/b5ff6f8dd8713c3a8d4864f2f975374f0612976b/src/analysis/functions.rs#L558) stuff btw.
