### ISSUE TITLE
Provide `gio::File::get_path()`

### ISSUE THREAD

**Issue by dwuertz** [gtk-rs/gtk-rs#515]
I need to extract the path from a gio::File, i.e. a wrapper method around g_file_get_path().

```
impl File {
    pub fn get_path(&self) -> std::path::PathBuf {
    }
}
```

Use case: gtk:4::prelude::FileChooserExt only returns the selection as gio::File. So, I can't use it with any API that requires a std::path::Path.

**Comment by bilelmoussaoui** [comment]
Such method already exists https://gtk-rs.org/gtk-rs/git/docs/gio/prelude/trait.FileExt.html#tymethod.path ?

**Comment by dwuertz** [comment]
You're right, I totally missed that, sorry for the noise! Closing
