### ISSUE TITLE
Export macros in a Rust 2018 friendly way

### ISSUE THREAD

**Issue by alatiera** [gtk-rs/gtk-rs#56]
Before macros were imported with the `[macro_use]` attribute above the `extern crate` declaration. With rust 2018 though, this is no longer needed and macros can be imported with just use. Currently you would need to import weird paths to do so, and the codebase is not does not handle the new module system well.

Not sure how other crates handle this, or if exporting them in the prelude it will be enough, but ideally it would be something simple to do so.

ex. `use glib::prelude::glib_object_subclass`

**Comment by sdroege** [comment]
Macros are always exported from the crate root, even if they're defined in some sub-module. `use glib::glib_wrapper;` for example works just fine although it's defined in the `wrapper` module.
