### ISSUE TITLE
Manual implementation of enumerate_*

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk-rs#69]
Gio::File lacks enumerate_* that needs some manual bindings I guess. It would be nice to have them back
- [x] enumerate_children (attributes, flags, cancellable)
- [ ]  enumerate_children_async (attributes, flags, io_priority, cancellable, callback, *user_data)
- [ ] enumerate_children_finish (res)

**Comment by pbor** [comment]
working on it
