### ISSUE TITLE
All Context functions should return a Result instead of calling expect()

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/gtk-rs#74]
Things have gotten to a point in librsvg where most of the incoming bugs that make the library panic are due to cairo-rs calling `expect()` on an `Err` inside the `Context` methods.  (That is, rather than panicking in librsvg itself, something in the drawing calls causes the `cr` to enter an error state.)

For example, all of the `line_to` / `move_to` / etc. can set the `cr` to an out-of-memory state if they can't allocate the new command.  In theory, they could also set an error state if they detected coordinates outside Cairo's supported range (I intend to look into that soon - Cairo crashes really easily if given coordinates outside ±2^23, and it doesn't do range checking for coordinates).

I'd like to propose that either all the Context functions return a Result, or that we remove the expect()s and make `Context.status()` public again.

One thing librsvg would like to do, for example, is to feed a path to cairo with the `move_to`, `line_to`, etc. and just check at the end if there was an error.  It would also be fine to catch a result with `?` and return as early as possible if there is an error in one of the individual commands.

Cairo contexts and surfaces have the same "lenient" error checking - they can go into an error state and ignore further API calls, but this is just to help C programs avoid having `if (cairo_something(...) != OK)` everywhere.  We have better language facilities in Rust :smiley: 

Summary: 

* I think just returning a Result instead of calling expect() would let the calling program make the correct choice of what to do upon errors.

* I think we still want a public way to get the Context's status.  One thing librsvg does is to get a `*mut cairo_t` from the C world, then wraps it in a `Context` and checks to see if the context is in error - it will g_warning() and return if so, to avoid panicking inside librsvg/cairo-rs.

**Comment by pbor** [comment]
Isn't calling `status()` on every call too much?

It seems to me like we should check when calling `fill/stroke/paint/etc`, but not when building the path to draw...

**Comment by bilelmoussaoui** [comment]
Would be nice to know what's the plan here as I'm very interested in seeing librsvg getting an update to the latest glib stuff so that it's usable with gtk4

**Comment by federicomenaquintero** [comment]
You know, @pbor has a good point - from debugging some things in librsvg recently, it seems indeed useful to only check when something "commits" to a surface, but not on every individual drawing call.

(Right now, I'm debugging a panic where `cr.restore()`  finds out that the previous drawing caused the cr to be in error.  For librsvg, **that** point seems like a good place to figure out that the drawing "transaction" failed.)

**Comment by federicomenaquintero** [comment]
I've pushed some extra commits to my branch; somehow I forgot to push them before.

For a smaller change, it would be enough for librsvg to be able to know if the incoming `cairo_t` from C is in an error state.  We can probably live with not checking the status while drawing, and punt that until cairo-rs can return that information instead of calling `expect` itself.

**Comment by pbor** [comment]
This is one of the blocker to update the gtk-rs stack in librsvg. I suggest we try to identify a minimal path forward and then iterate incrementally.

My proposal would be.
1. re-expose `cairo_status` in the public API. I think that even if we start returning `Result` people would still find the ability to inspect the status useful during debug
2. Remove `expect` calls in the code
3. Return `Result` in some of the more obvious candidates

**Comment by sdroege** [comment]
> re-expose `cairo_status` in the public API. I think that even if we start returning `Result` people would still find the ability to inspect the status useful during debug

You could also expose it as a `fn check_status(&self) -> Result<(), AnEnumWithAllTheErrorCases>`. I think that would be a good idea and would work better with the ? operator.

**Comment by pbor** [comment]
> You could also expose it as a `fn check_status(&self) -> Result<(), AnEnumWithAllTheErrorCases>`. I think that would be a good idea and would work better with the ? operator.

That's already the case, no? We currently have 

```
    pub(crate) fn status(&self) -> Result<(), Error> {
        let status = unsafe { ffi::cairo_status(self.0.as_ptr()) };
        status_to_result(status)
    }
```

and `Error` is an enum

**Comment by bilelmoussaoui** [comment]
> > You could also expose it as a `fn check_status(&self) -> Result<(), AnEnumWithAllTheErrorCases>`. I think that would be a good idea and would work better with the ? operator.
> 
> That's already the case, no? We currently have
> 
> ```
>     pub(crate) fn status(&self) -> Result<(), Error> {
>         let status = unsafe { ffi::cairo_status(self.0.as_ptr()) };
>         status_to_result(status)
>     }
> ```
> 
> and `Error` is an enum

Yes, we just need to make the status public again

**Comment by pbor** [comment]
If #279 gets merged, my proposed next steps would be:

1. Cherry pick this commit from @federicomenaquintero 's branch: https://github.com/federicomenaquintero/cairo/commit/816d4e00a88d17dd32dda18704ca0995a063069f which helps that checking that context creation succeeded
2. Remove all existing `expects()` in the setters

After that is done, we can probably discuss which ones of the other functions need to return a `Result`.

**Comment by GuillaumeGomez** [comment]
> After that is done, we can probably discuss which ones of the other functions need to return a `Result`.

I'd say all of them. :)

**Comment by pbor** [comment]
> I'd say all of them. :)

I do not agree :)
See the discussion in the thread above. I think we should return a `Result` only when "committing" to a surface with `draw()` etc.
Not when building the path to draw and setting the cr properties.

**Comment by sdroege** [comment]
How should we move forward with this?

**Comment by GuillaumeGomez** [comment]
cc @federicomenaquintero

**Comment by federicomenaquintero** [comment]
So, let's confirm:

* I *think* it's fine to only return `Result` at `fill`, `stroke`, etc. - the functions that frob the surface from the cr.
* Returning `Result` from `line_to` / etc. - the functions that only cause small allocations, whose failure means you are *really* screwed generally - sounds nice, but probably overkill?
* No `expect()` anywhere so apps don't panic.
* I'm rather worried about the `Self::from_raw_full(ptr).unwrap()` pattern.  I think I'd rather have `from_raw_full` be infallible, or return a `Result<Context, (Context, cairo::Error)>` - meaning that you can indeed have a context that is in an error state.  This seems consistent with making `.status()` public again.

Thoughts?

**Comment by sdroege** [comment]
Sounds reasonable to me

**Comment by GuillaumeGomez** [comment]
I completely agree.

**Comment by sdroege** [comment]
@federicomenaquintero We're planning to release soonish. Do you think this could be finished in the next days?

**Comment by federicomenaquintero** [comment]
As far as I can see from the current state of the code (please correct me if I'm wrong):

`Context::from_raw_*()` return a `Context` which can be in an error state, and which can be examined with `.status()`.  This removes my main source of anxiety from librsvg - that an incoming `cairo_t *` could already be in error.  So, no changes needed there, unless we want to go for the `from_raw_*() -> Result<Context, (Context, cairo::Error)>` scheme, to catch errored contexts early?  This may make C APIs implemented in Rust easier to get correct; I'm not sure.

`Context::from_glib_*()` no longer unwrap/expect; this is good.

`context.rs` still has a bunch of `.expect()` calls.  I think these are all in methods that modify the `cairo_t` but not the target surface, and I think we should remove all of them.  Calls that validate their arguments like `set_dash` can set the `cr` in an error state if the args are invalid, but this should be visible when the caller tries to commit to the target surface with fill/stroke/etc.

`set_source` takes a `Pattern`, which can be in an error state.  In the C code, doing this marks the `cairo_t` as being in error as well.  Maybe we should do `set_source(&self, source: &Pattern) -> Result<(), cairo::Error>` and check the source's status before calling `cairo_set_source`?

Which functions to return a `Result` from? From reading bits of `cairo/src/cairo.c`:
 * `new` to catch the surface already being in an error state
 * `pop_group` because its result depends on the whole group procedure.
 * `pop_group_to_source` - same
 * `set_source` - as discussed above.
 * All the functions with a return value, or with inout parameters - these return meaningless values if the `cairo_t` is in error:  `clip_extents`, `in_clip`, `fill_extents`, `in_fill`, `stroke_extents`, `in_stroke`, `user_to_device_distance`, `device_to_user`, `device_to_user_distance`, `font_extents`, `text_extents`, `glyph_extents`, `copy_path`, `copy_path_flat`, `has_current_point`, `current_point`, `path_extents`.
 * All the functions that modify the target surface: `fill`, `fill_preserve`, `mask` (also depends on the status of the passed pattern), `mask_surface` (same), `paint, `paint_with_alpha`, `stroke`, `stroke_preserve`, `copy_page`, `show_page`, `show_text`, `show_glyphs`, `show_text_glyphs`.

**Comment by federicomenaquintero** [comment]
@bilelmoussaoui I've started https://github.com/federicomenaquintero/gtk-rs/commits/context-result for if you want to pick it up from there.
