### ISSUE TITLE
Document how to do an image that is redrawn/updated

### ISSUE THREAD

**Issue by penguin42** [gtk-rs/gtk-rs#81]
Hi,
  I've just managed to get something to work, but something that telling me how to do it properly would have been better!
I've got a fractal renderer that renders into a buffer (with OpenCL), and I want to be able to do a callback that causes it to be re-rendered.   I'm using a Gtk::Image to display the image.  In the end I ended up using a Cairo ImageSurface and using get_data() to get the buffer to pass into the ocl buffer read() method;  What took me longer to figure out was that since get_data() fails with non-exclusive as soon as the ImageSurface is associated with the Image, my redraw code has to do  set_from_surface(None) before the get_data() and then set_from_surface again with the real value.
That's something that coming from C is non-obvious and I don't think there's any current doc explaining how to do it.

**Comment by sdroege** [comment]
There's a solution for this in https://github.com/gtk-rs/gtk-rs/issues/75 and that should be documented.
