### ISSUE TITLE
Support for non-owned backend buffers

### ISSUE THREAD

**Issue by vberger** [gtk-rs/gtk-rs#82]
For a wayland use-case, a classic way to draw a window without using OpenGL/Vulkan is to do software rendering using Cairo.

To do so, the process is:
- create a shared memory pool with the compositor
- allocate a buffer in this memory pool
- create a cairo surface using this buffer
- draw

Translated to Rust, it means creating an `ImageSurface` from a `&mut [u8]`, which does not look to be possible at the moment, while being a common pattern in C programs.

**Comment by sdroege** [comment]
This can be done with https://github.com/gtk-rs/gtk-rs/commit/59f08d951a391e4e282ea02b9c65f0e21a07e480#diff-b57e332c0210453eaa97fc614caa7d61327cdf28c75e5e653075a5d4ea3ea6b5 now with some `unsafe` code as it's your responsibility then to ensure the surface does not outlive the data.
