### ISSUE TITLE
Improve null pointer handling

### ISSUE THREAD

**Issue by abonander** [gtk-rs/gtk-rs#92]
Many parts of this crate's API as well as some of the related ones return `Option` to handle when a pointer returned from an FFI call is null. Unless the C API documentation says why a returned pointer might be null, it is probably safe to assume that a null pointer means something bad happened and the program shouldn't continue (e.g. allocation failure/OOM). Overuse of `Option` for little good reason when they would usually prefer to unwrap it anyways pollutes client code and reduces ergonomics.

**Comment by sdroege** [comment]
This is solved by https://github.com/gtk-rs/gir/pull/970 to some degree. GLib already makes use of the nullable annotations correctly, GIO will after [this MR](https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1708) is in GIO and @sophie-h was looking at the situation in GTK. It just needs to be done one after another.
