### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by lucaswerkmeister** [gtk-rs/gtk-rs#93]
- [ ] [Save to file](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-File-saving.html)
  - For the start, just having [`gdk_pixbuf_save()`](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-File-saving.html#gdk-pixbuf-save) without save parameters would be nice, and probably sufficient for many applications.
  - **Unassigned**
- [ ] [`Pixbuf::fill()`](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Utilities.html#gdk-pixbuf-fill)
  - one `i32` or `u32` parameter, or four `rgba` parameters?
  - **Unassigned**

**Comment by sdroege** [comment]
These functions exist since a while.
