### ISSUE TITLE
Cursor manipulations don't seem to be possible

### ISSUE THREAD

**Issue by mwm** [gtk-rs/gtk-rs#96]
Two issues, but they seem to be related. Let me know if you want them split.

First, `Cursor::Type` doesn't seem to be properly exposed. If I try t compile this:

```
extern crate gdk;
use gdk::prelude::*;
use gdk;

fn main () {
    println!("{:?}", gdk::Cursor::Type::Watch);
}
```

I get this error:

>    Compiling order_chaos v0.1.0 (file:///export/mwm/src/chiselapp/order_chaos)
> gtk.rs:212:59: 212:83 error: no associated item named `Watch` found for type `gdk_sys::GdkCursorType` in the current scope
> gtk.rs:212                                                           gdk::cursor::Type::Watch)));

It works if I use the `gdk-sys` crate and `gdk_sys::GdkCursorType::Watch`, which I believe should be the same thing.

Second, the type for the various gdk `set_cursor` routines seems to b e wrong. Quoting the docs:

> fn set_cursor(&self, cursor: &Cursor)[−]
> 
> Sets the default mouse pointer for a Window.
> 
> Note that cursor must be for the same display as self.
> 
> Use Cursor::new_for_display or Cursor::new_from_pixbuf to create the cursor. To make the cursor invisible, use CursorType::BlankCursor. Passing None for the cursor argument to Window::set_cursor means that self will use the cursor of its parent window. Most windows should use this default.

Ok, how exactly am I supposed to pass `None` for the cursor argument to put things back, as that isn't an `Option` argument. Or is there some other `None` I should be using?

This is my first program using either Rust or gdk, so apologies in the likely event that I've overlooked something obvious.

**Comment by sdroege** [comment]
The relevant API is included in the bindings since a long time.
