### ISSUE TITLE
Add Selections constants

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk-rs#98]
Pertains to `GDK_SELECTION_*`, `GDK_TARGET_*`, and `GDK_SELECTION_TYPE_*` [reference](https://developer.gnome.org/gdk3/stable/gdk3-Selections.html).

I think these should go in `src/selections.rs`, and I'd implement them manually, but unlike other constants already exposed by `gdk`, these do not already exist in `gdk_ffi`. What's the proper procedure here then? Should these somehow be exposed in `gdk_sys` first and then re-exported with better names here?

This was broken out of gtk-rs/gdk#148.

**Comment by pbor** [comment]
In `gdk/src/lib.rs` I already see:

```
pub use crate::atom::SELECTION_CLIPBOARD;
pub use crate::atom::SELECTION_PRIMARY;
pub use crate::atom::SELECTION_SECONDARY;
pub use crate::atom::SELECTION_TYPE_ATOM;
pub use crate::atom::SELECTION_TYPE_BITMAP;
pub use crate::atom::SELECTION_TYPE_COLORMAP;
pub use crate::atom::SELECTION_TYPE_DRAWABLE;
pub use crate::atom::SELECTION_TYPE_INTEGER;
pub use crate::atom::SELECTION_TYPE_PIXMAP;
pub use crate::atom::SELECTION_TYPE_STRING;
pub use crate::atom::SELECTION_TYPE_WINDOW;
pub use crate::atom::TARGET_BITMAP;
pub use crate::atom::TARGET_COLORMAP;
pub use crate::atom::TARGET_DRAWABLE;
pub use crate::atom::TARGET_PIXMAP;
pub use crate::atom::TARGET_STRING;
```

Are we missing anything?

**Comment by sdroege** [comment]
Looks like an old issue that was never closed.
